export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  CENTRAL_MINISTRY_OFFICER: 'CENTRAL_MINISTRY_OFFICER',
  STATE_GOV_OFFICER: 'STATE_GOV_OFFICER',
  DISTRICT_AUTHORITY_OFFICER: 'DISTRICT_AUTHORITY_OFFICER',
  LAND_ACQUISITION_OFFICER: 'LAND_ACQUISITION_OFFICER',
  PROJECT_AGENCY_OFFICER: 'PROJECT_AGENCY_OFFICER',
  FIELD_SURVEY_OFFICER: 'FIELD_SURVEY_OFFICER',
  VIEWER_EXECUTIVE: 'VIEWER_EXECUTIVE'
};

export const PERMISSIONS = {
  VIEW_PROJECTS: 'VIEW_PROJECTS',
  CREATE_PROJECTS: 'CREATE_PROJECTS',
  SUBMIT_PROPOSALS: 'SUBMIT_PROPOSALS',
  APPROVE_PROPOSALS: 'APPROVE_PROPOSALS',
  ADVANCE_STATUTORY_STAGE: 'ADVANCE_STATUTORY_STAGE',

  VIEW_PARCELS: 'VIEW_PARCELS',
  EDIT_PARCEL: 'EDIT_PARCEL',
  GEOTAG_FIELD_SURVEY: 'GEOTAG_FIELD_SURVEY',
  VIEW_GIS_MAP: 'VIEW_GIS_MAP',

  PUBLISH_SECTION_11: 'PUBLISH_SECTION_11',
  HEAR_SECTION_15_OBJECTIONS: 'HEAR_SECTION_15_OBJECTIONS',
  DECLARE_SECTION_19: 'DECLARE_SECTION_19',
  VIEW_NOTIFICATIONS: 'VIEW_NOTIFICATIONS',

  CALCULATE_SOLATIUM: 'CALCULATE_SOLATIUM',
  PASS_SECTION_23_AWARD: 'PASS_SECTION_23_AWARD',
  DISBURSE_PFMS_DBT: 'DISBURSE_PFMS_DBT',

  ISSUE_POSSESSION_CERTIFICATE: 'ISSUE_POSSESSION_CERTIFICATE',
  VIEW_POSSESSION: 'VIEW_POSSESSION',

  VIEW_RR: 'VIEW_RR',
  MANAGE_RR: 'MANAGE_RR',
  VIEW_FAMILIES: 'VIEW_FAMILIES',
  ENROLL_FAMILY: 'ENROLL_FAMILY',

  VIEW_DOCUMENTS: 'VIEW_DOCUMENTS',
  VIEW_REPORTS: 'VIEW_REPORTS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  ADMIN_SETTINGS: 'ADMIN_SETTINGS'
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.CENTRAL_MINISTRY_OFFICER]: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.CREATE_PROJECTS,
    PERMISSIONS.SUBMIT_PROPOSALS,
    PERMISSIONS.APPROVE_PROPOSALS,
    PERMISSIONS.VIEW_GIS_MAP,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],

  [ROLES.STATE_GOV_OFFICER]: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.CREATE_PROJECTS,
    PERMISSIONS.APPROVE_PROPOSALS,
    PERMISSIONS.ADVANCE_STATUTORY_STAGE,
    PERMISSIONS.VIEW_PARCELS,
    PERMISSIONS.VIEW_GIS_MAP,
    PERMISSIONS.PUBLISH_SECTION_11,
    PERMISSIONS.DECLARE_SECTION_19,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],

  [ROLES.DISTRICT_AUTHORITY_OFFICER]: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.APPROVE_PROPOSALS,
    PERMISSIONS.ADVANCE_STATUTORY_STAGE,
    PERMISSIONS.VIEW_PARCELS,
    PERMISSIONS.EDIT_PARCEL,
    PERMISSIONS.VIEW_GIS_MAP,
    PERMISSIONS.PUBLISH_SECTION_11,
    PERMISSIONS.HEAR_SECTION_15_OBJECTIONS,
    PERMISSIONS.DECLARE_SECTION_19,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.CALCULATE_SOLATIUM,
    PERMISSIONS.PASS_SECTION_23_AWARD,
    PERMISSIONS.VIEW_POSSESSION,
    PERMISSIONS.ISSUE_POSSESSION_CERTIFICATE,
    PERMISSIONS.VIEW_RR,
    PERMISSIONS.MANAGE_RR,
    PERMISSIONS.VIEW_FAMILIES,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],

  [ROLES.LAND_ACQUISITION_OFFICER]: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.ADVANCE_STATUTORY_STAGE,
    PERMISSIONS.VIEW_PARCELS,
    PERMISSIONS.EDIT_PARCEL,
    PERMISSIONS.VIEW_GIS_MAP,
    PERMISSIONS.PUBLISH_SECTION_11,
    PERMISSIONS.HEAR_SECTION_15_OBJECTIONS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.CALCULATE_SOLATIUM,
    PERMISSIONS.PASS_SECTION_23_AWARD,
    PERMISSIONS.DISBURSE_PFMS_DBT,
    PERMISSIONS.VIEW_POSSESSION,
    PERMISSIONS.ISSUE_POSSESSION_CERTIFICATE,
    PERMISSIONS.VIEW_RR,
    PERMISSIONS.MANAGE_RR,
    PERMISSIONS.VIEW_FAMILIES,
    PERMISSIONS.ENROLL_FAMILY,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],

  [ROLES.PROJECT_AGENCY_OFFICER]: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.CREATE_PROJECTS,
    PERMISSIONS.SUBMIT_PROPOSALS,
    PERMISSIONS.VIEW_PARCELS,
    PERMISSIONS.VIEW_GIS_MAP,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.CALCULATE_SOLATIUM,
    PERMISSIONS.DISBURSE_PFMS_DBT,
    PERMISSIONS.VIEW_POSSESSION,
    PERMISSIONS.VIEW_RR,
    PERMISSIONS.VIEW_FAMILIES,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS
  ],

  [ROLES.FIELD_SURVEY_OFFICER]: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.VIEW_PARCELS,
    PERMISSIONS.EDIT_PARCEL,
    PERMISSIONS.GEOTAG_FIELD_SURVEY,
    PERMISSIONS.VIEW_GIS_MAP,
    PERMISSIONS.VIEW_FAMILIES,
    PERMISSIONS.ENROLL_FAMILY,
    PERMISSIONS.VIEW_DOCUMENTS
  ],

  [ROLES.VIEWER_EXECUTIVE]: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.VIEW_GIS_MAP,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS
  ]
};

// Route permission requirements map
export const ROUTE_PERMISSIONS = {
  '/dashboard': null, // All authenticated officers can view dashboard
  '/profile': null,   // All authenticated officers can view their profile
  '/projects': PERMISSIONS.VIEW_PROJECTS,
  '/projects/:id': PERMISSIONS.VIEW_PROJECTS,
  '/proposals': PERMISSIONS.SUBMIT_PROPOSALS,
  '/land-parcels': PERMISSIONS.VIEW_PARCELS,
  '/gis-map': PERMISSIONS.VIEW_GIS_MAP,
  '/notifications': PERMISSIONS.VIEW_NOTIFICATIONS,
  '/awards': PERMISSIONS.PASS_SECTION_23_AWARD,
  '/compensation': PERMISSIONS.CALCULATE_SOLATIUM,
  '/possession': PERMISSIONS.VIEW_POSSESSION,
  '/rr': PERMISSIONS.VIEW_RR,
  '/families': PERMISSIONS.VIEW_FAMILIES,
  '/documents': PERMISSIONS.VIEW_DOCUMENTS,
  '/reports': PERMISSIONS.VIEW_REPORTS,
  '/analytics': PERMISSIONS.VIEW_ANALYTICS,
  '/audit-logs': PERMISSIONS.VIEW_AUDIT_LOGS,
  '/admin': PERMISSIONS.ADMIN_SETTINGS
};

export const hasPermission = (user, permission) => {
  if (!user || !user.role) return false;
  if (user.role === ROLES.SUPER_ADMIN) return true;
  if (!permission) return true;
  const permissions = ROLE_PERMISSIONS[user.role] || [];
  return permissions.includes(permission);
};

export const canAccessRoute = (user, routePath) => {
  if (!user) return false;
  if (user.role === ROLES.SUPER_ADMIN) return true;
  const required = ROUTE_PERMISSIONS[routePath];
  if (!required) return true;
  return hasPermission(user, required);
};
