const bcrypt = require('bcryptjs');
const { ROLES } = require('../config/roles');

async function getSeedData() {
  const salt = await bcrypt.genSalt(10);
  const passwordHash = await bcrypt.hash('Admin@123', salt);

  // 1. STATUTORY USERS (8 Statutory Personas)
  const users = [
    {
      _id: 'user_001',
      id: 'user_001',
      name: 'Dr. Rajeshwar Sharma, IAS',
      email: 'superadmin@bhoomisetu.gov.in',
      password: passwordHash,
      role: ROLES.SUPER_ADMIN,
      designation: 'Principal Secretary & National DG (Land Resources)',
      department: 'Ministry of Rural Development / NIC',
      jurisdiction: { state: 'National', district: 'All', tehsil: 'All' },
      phone: '+91 98112 00001'
    },
    {
      _id: 'user_002',
      id: 'user_002',
      name: 'Smt. Ananya Sen, IRTS',
      email: 'ministry.morth@bhoomisetu.gov.in',
      password: passwordHash,
      role: ROLES.CENTRAL_MINISTRY_OFFICER,
      designation: 'Joint Secretary (Infrastructure & Land Acquisition)',
      department: 'Ministry of Road Transport and Highways (MoRTH)',
      jurisdiction: { state: 'National', district: 'All', tehsil: 'All' },
      phone: '+91 98112 00002'
    },
    {
      _id: 'user_003',
      id: 'user_003',
      name: 'Shri Vikramaditya Jadhav, IAS',
      email: 'state.revenue@bhoomisetu.gov.in',
      password: passwordHash,
      role: ROLES.STATE_GOV_OFFICER,
      designation: 'Divisional Commissioner & Secretary (Revenue)',
      department: 'Revenue & Forest Department, Govt of Maharashtra',
      jurisdiction: { state: 'Maharashtra', district: 'Konkan Division', tehsil: 'All' },
      phone: '+91 98112 00003'
    },
    {
      _id: 'user_004',
      id: 'user_004',
      name: 'Shri Ashok Kumar Meena, IAS',
      email: 'dm.thane@bhoomisetu.gov.in',
      password: passwordHash,
      role: ROLES.DISTRICT_AUTHORITY_OFFICER,
      designation: 'District Magistrate & Collector, Thane',
      department: 'District Revenue Administration',
      jurisdiction: { state: 'Maharashtra', district: 'Thane', tehsil: 'Bhiwandi & Kalyan' },
      phone: '+91 98112 00004'
    },
    {
      _id: 'user_005',
      id: 'user_005',
      name: 'Shri Suresh K. Patil',
      email: 'cala.nhai@bhoomisetu.gov.in',
      password: passwordHash,
      role: ROLES.LAND_ACQUISITION_OFFICER,
      designation: 'Competent Authority for Land Acquisition (CALA) & Deputy Collector',
      department: 'Special Land Acquisition Office No. 2',
      jurisdiction: { state: 'Maharashtra', district: 'Thane', tehsil: 'Bhiwandi' },
      phone: '+91 98112 00005'
    },
    {
      _id: 'user_006',
      id: 'user_006',
      name: 'Er. Manoj Verma',
      email: 'agency.nhai@bhoomisetu.gov.in',
      password: passwordHash,
      role: ROLES.PROJECT_AGENCY_OFFICER,
      designation: 'Chief General Manager & Project Director (PIU Mumbai-Vadodara)',
      department: 'National Highways Authority of India (NHAI)',
      jurisdiction: { state: 'Maharashtra / Gujarat', district: 'All', tehsil: 'All' },
      phone: '+91 98112 00006'
    },
    {
      _id: 'user_007',
      id: 'user_007',
      name: 'Shri Santosh Yadav',
      email: 'surveyor.amin@bhoomisetu.gov.in',
      password: passwordHash,
      role: ROLES.FIELD_SURVEY_OFFICER,
      designation: 'Senior Revenue Amin & Field Surveyor',
      department: 'Land Records & Cadastral Survey Division',
      jurisdiction: { state: 'Maharashtra', district: 'Thane', tehsil: 'Bhiwandi' },
      phone: '+91 98112 00007'
    },
    {
      _id: 'user_008',
      id: 'user_008',
      name: 'Dr. Meenakshi Sundaram',
      email: 'executive.viewer@bhoomisetu.gov.in',
      password: passwordHash,
      role: ROLES.VIEWER_EXECUTIVE,
      designation: 'Senior Advisor (PM GatiShakti National Master Plan)',
      department: 'Department for Promotion of Industry and Internal Trade (DPIIT)',
      jurisdiction: { state: 'National', district: 'All', tehsil: 'All' },
      phone: '+91 98112 00008'
    }
  ];

  // 2. 10 MAJOR INFRASTRUCTURE PROJECTS ACROSS 10 INDIAN STATES & 8 PROJECT TYPES
  const projects = [
    {
      _id: 'proj_001_dme',
      id: 'proj_001_dme',
      projectId: 'PRJ-NHAI-DME-001',
      projectCode: 'PRJ-NHAI-DME-001',
      projectName: 'Delhi-Mumbai Expressway (Vadodara-JNPT Spur Package 14)',
      title: 'Delhi-Mumbai Expressway (Vadodara-JNPT Spur Package 14)',
      projectType: 'Highway',
      sector: 'Highway',
      description: 'Access-controlled 8-lane greenfield expressway connecting JNPT Port to Vadodara-Mumbai corridor, bypassing congested arterial routes.',
      ministry: 'Ministry of Road Transport and Highways (MoRTH)',
      implementingAgency: 'National Highways Authority of India (NHAI)',
      state: 'Maharashtra',
      district: 'Thane',
      tehsil: 'Bhiwandi',
      village: 'Padgha',
      statesCovered: ['Maharashtra'],
      districtsCovered: ['Thane'],
      tehsilsCovered: ['Bhiwandi'],
      villagesCovered: ['Padgha', 'Khadavali', 'Borivali-T'],
      totalProjectArea: 450.0,
      requiredLandArea: 320.5,
      targetAcquisitionAreaHectares: 320.5,
      acquiredLandArea: 245.8,
      acquiredAreaHectares: 245.8,
      estimatedBudgetCrores: 3450,
      estimatedCostInCrores: 3450,
      compensationDisbursedCrores: 482.4,
      currentStage: 'SECTION_23_AWARD_PASSED',
      status: 'Active Acquisition',
      startDate: new Date('2024-01-15'),
      expectedCompletionDate: new Date('2026-12-31'),
      assignedOfficers: {
        calaOfficerName: 'Shri Suresh K. Patil',
        districtOfficerName: 'Shri Ashok Kumar Meena, IAS',
        surveyorOfficerName: 'Shri Santosh Yadav'
      },
      khasraCount: 148,
      affectedFamiliesCount: 84
    },
    {
      _id: 'proj_002_dfc',
      id: 'proj_002_dfc',
      projectId: 'PRJ-MOR-WDFC-002',
      projectCode: 'PRJ-MOR-WDFC-002',
      projectName: 'Western Dedicated Freight Corridor (Surat-Palanpur Section)',
      title: 'Western Dedicated Freight Corridor (Surat-Palanpur Section)',
      projectType: 'Railway',
      sector: 'Railway',
      description: 'Heavy-haul double-stack container electrified railway corridor linking western industrial heartland to Jawaharlal Nehru Port.',
      ministry: 'Ministry of Railways',
      implementingAgency: 'Dedicated Freight Corridor Corporation of India (DFCCIL)',
      state: 'Gujarat',
      district: 'Surat',
      tehsil: 'Choryasi',
      village: 'Sachin',
      statesCovered: ['Gujarat'],
      districtsCovered: ['Surat'],
      tehsilsCovered: ['Choryasi'],
      villagesCovered: ['Sachin', 'Udhna', 'Bhestan'],
      totalProjectArea: 280.0,
      requiredLandArea: 210.0,
      targetAcquisitionAreaHectares: 210.0,
      acquiredLandArea: 210.0,
      acquiredAreaHectares: 210.0,
      estimatedBudgetCrores: 4890,
      estimatedCostInCrores: 4890,
      compensationDisbursedCrores: 720.0,
      currentStage: 'POSSESSION_TAKEN',
      status: 'Possession Taken',
      startDate: new Date('2023-08-01'),
      expectedCompletionDate: new Date('2026-06-30'),
      assignedOfficers: {
        calaOfficerName: 'Shri H. R. Patel, GAS',
        districtOfficerName: 'Dr. Ayush Sharma, IAS',
        surveyorOfficerName: 'Shri Govindbhai Parmar'
      },
      khasraCount: 112,
      affectedFamiliesCount: 65
    },
    {
      _id: 'proj_003_ganga',
      id: 'proj_003_ganga',
      projectId: 'PRJ-UPEIDA-GNGA-003',
      projectCode: 'PRJ-UPEIDA-GNGA-003',
      projectName: 'Ganga Expressway Greenfield Corridor Phase-II',
      title: 'Ganga Expressway Greenfield Corridor Phase-II',
      projectType: 'Highway',
      sector: 'Highway',
      description: 'High-speed 6-lane expandable to 8-lane expressway connecting Meerut to Prayagraj across major agricultural and industrial nodes.',
      ministry: 'Ministry of Road Transport and Highways (MoRTH)',
      implementingAgency: 'Uttar Pradesh Expressways Industrial Development Authority (UPEIDA)',
      state: 'Uttar Pradesh',
      district: 'Prayagraj',
      tehsil: 'Soraon',
      village: 'Mandawa',
      statesCovered: ['Uttar Pradesh'],
      districtsCovered: ['Prayagraj'],
      tehsilsCovered: ['Soraon'],
      villagesCovered: ['Mandawa', 'Mauaima', 'Holagarh'],
      totalProjectArea: 600.0,
      requiredLandArea: 480.0,
      targetAcquisitionAreaHectares: 480.0,
      acquiredLandArea: 120.0,
      acquiredAreaHectares: 120.0,
      estimatedBudgetCrores: 5200,
      estimatedCostInCrores: 5200,
      compensationDisbursedCrores: 195.5,
      currentStage: 'SECTION_11_NOTIFIED',
      status: 'Active Acquisition',
      startDate: new Date('2024-03-01'),
      expectedCompletionDate: new Date('2027-03-31'),
      assignedOfficers: {
        calaOfficerName: 'Shri R. P. Maurya, PCS',
        districtOfficerName: 'Shri Manish Verma, IAS',
        surveyorOfficerName: 'Shri Ramswaroop Lal'
      },
      khasraCount: 220,
      affectedFamiliesCount: 130
    },
    {
      _id: 'proj_004_cbic',
      id: 'proj_004_cbic',
      projectId: 'PRJ-NICDC-CBIC-004',
      projectCode: 'PRJ-NICDC-CBIC-004',
      projectName: 'Chennai-Bengaluru Industrial Corridor (Ponneri Node)',
      title: 'Chennai-Bengaluru Industrial Corridor (Ponneri Node)',
      projectType: 'Industrial Corridor',
      sector: 'Industrial Corridor',
      description: 'Smart industrial node development under National Industrial Corridor programme to establish world-class electronics and EV manufacturing.',
      ministry: 'Ministry of Commerce & Industry (DPIIT)',
      implementingAgency: 'National Industrial Corridor Development Corporation (NICDC)',
      state: 'Tamil Nadu',
      district: 'Tiruvallur',
      tehsil: 'Ponneri',
      village: 'Kattupalli',
      statesCovered: ['Tamil Nadu'],
      districtsCovered: ['Tiruvallur'],
      tehsilsCovered: ['Ponneri'],
      villagesCovered: ['Kattupalli', 'Ennore', 'Vanjivakkam'],
      totalProjectArea: 500.0,
      requiredLandArea: 350.0,
      targetAcquisitionAreaHectares: 350.0,
      acquiredLandArea: 280.0,
      acquiredAreaHectares: 280.0,
      estimatedBudgetCrores: 2850,
      estimatedCostInCrores: 2850,
      compensationDisbursedCrores: 410.0,
      currentStage: 'SECTION_19_DECLARED',
      status: 'Active Acquisition',
      startDate: new Date('2023-11-10'),
      expectedCompletionDate: new Date('2026-09-30'),
      assignedOfficers: {
        calaOfficerName: 'Tmt. K. Vasanthi, DRO',
        districtOfficerName: 'Dr. T. Prabhu, IAS',
        surveyorOfficerName: 'Thiru S. Murugan'
      },
      khasraCount: 175,
      affectedFamiliesCount: 95
    },
    {
      _id: 'proj_005_ukp',
      id: 'proj_005_ukp',
      projectId: 'PRJ-KRN-UKP3-005',
      projectCode: 'PRJ-KRN-UKP3-005',
      projectName: 'Upper Krishna Irrigation & Canal Project Stage-III',
      title: 'Upper Krishna Irrigation & Canal Project Stage-III',
      projectType: 'Irrigation',
      sector: 'Irrigation',
      description: 'Major command area irrigation canal network to irrigate 5.3 lakh hectares across drought-prone northern Karnataka river basins.',
      ministry: 'Ministry of Jal Shakti',
      implementingAgency: 'Krishna Bhagya Jala Nigam Limited (KBJNL)',
      state: 'Karnataka',
      district: 'Bagalkote',
      tehsil: 'Bilagi',
      village: 'Galgali',
      statesCovered: ['Karnataka'],
      districtsCovered: ['Bagalkote'],
      tehsilsCovered: ['Bilagi'],
      villagesCovered: ['Galgali', 'Mamadapur', 'Sunag'],
      totalProjectArea: 750.0,
      requiredLandArea: 620.0,
      targetAcquisitionAreaHectares: 620.0,
      acquiredLandArea: 310.0,
      acquiredAreaHectares: 310.0,
      estimatedBudgetCrores: 3100,
      estimatedCostInCrores: 3100,
      compensationDisbursedCrores: 290.0,
      currentStage: 'SECTION_15_OBJECTIONS_REVIEWED',
      status: 'Active Acquisition',
      startDate: new Date('2024-02-01'),
      expectedCompletionDate: new Date('2027-06-30'),
      assignedOfficers: {
        calaOfficerName: 'Shri B. M. Hiremath, KAS',
        districtOfficerName: 'Shri Janardhan R., IAS',
        surveyorOfficerName: 'Shri Basavaraj S.'
      },
      khasraCount: 260,
      affectedFamiliesCount: 155
    },
    {
      _id: 'proj_006_kurnool',
      id: 'proj_006_kurnool',
      projectId: 'PRJ-MNRE-KRNL-006',
      projectCode: 'PRJ-MNRE-KRNL-006',
      projectName: 'Kurnool Ultra Mega Hybrid Solar & Wind Renewable Energy Park',
      title: 'Kurnool Ultra Mega Hybrid Solar & Wind Renewable Energy Park',
      projectType: 'Renewable Energy',
      sector: 'Renewable Energy',
      description: '1,200 MW utility-scale solar-wind hybrid clean energy park with co-located battery energy storage systems (BESS).',
      ministry: 'Ministry of New and Renewable Energy (MNRE)',
      implementingAgency: 'Solar Energy Corporation of India (SECI)',
      state: 'Andhra Pradesh',
      district: 'Kurnool',
      tehsil: 'Orvakal',
      village: 'Gani',
      statesCovered: ['Andhra Pradesh'],
      districtsCovered: ['Kurnool'],
      tehsilsCovered: ['Orvakal'],
      villagesCovered: ['Gani', 'Sakunala', 'Meedivemula'],
      totalProjectArea: 650.0,
      requiredLandArea: 540.0,
      targetAcquisitionAreaHectares: 540.0,
      acquiredLandArea: 540.0,
      acquiredAreaHectares: 540.0,
      estimatedBudgetCrores: 2100,
      estimatedCostInCrores: 2100,
      compensationDisbursedCrores: 380.0,
      currentStage: 'POSSESSION_TAKEN',
      status: 'Possession Taken',
      startDate: new Date('2023-05-15'),
      expectedCompletionDate: new Date('2025-11-30'),
      assignedOfficers: {
        calaOfficerName: 'Shri P. Srinivasulu, Revenue Div Officer',
        districtOfficerName: 'Dr. G. Srijana, IAS',
        surveyorOfficerName: 'Shri K. Venkat'
      },
      khasraCount: 190,
      affectedFamiliesCount: 78
    },
    {
      _id: 'proj_007_defense',
      id: 'proj_007_defense',
      projectId: 'PRJ-MOD-DRDO-007',
      projectCode: 'PRJ-MOD-DRDO-007',
      projectName: 'National Strategic Naval Radar & Coastal Defense Facility',
      title: 'National Strategic Naval Radar & Coastal Defense Facility',
      projectType: 'Defense',
      sector: 'Defense',
      description: 'High-security coastal surveillance radar, electronic testing enclave, and naval telemetry station under Ministry of Defence.',
      ministry: 'Ministry of Defence (MoD)',
      implementingAgency: 'Defence Research and Development Organisation (DRDO)',
      state: 'Odisha',
      district: 'Balasore',
      tehsil: 'Chandipur',
      village: 'Balaramgadi',
      statesCovered: ['Odisha'],
      districtsCovered: ['Balasore'],
      tehsilsCovered: ['Chandipur'],
      villagesCovered: ['Balaramgadi', 'Mirzapur', 'Kasinagar'],
      totalProjectArea: 350.0,
      requiredLandArea: 290.0,
      targetAcquisitionAreaHectares: 290.0,
      acquiredLandArea: 290.0,
      acquiredAreaHectares: 290.0,
      estimatedBudgetCrores: 1950,
      estimatedCostInCrores: 1950,
      compensationDisbursedCrores: 310.0,
      currentStage: 'POSSESSION_TAKEN',
      status: 'Possession Taken',
      startDate: new Date('2023-04-10'),
      expectedCompletionDate: new Date('2025-12-31'),
      assignedOfficers: {
        calaOfficerName: 'Shri D. K. Jena, OAS (SAG)',
        districtOfficerName: 'Shri D. B. Sahoo, IAS',
        surveyorOfficerName: 'Shri Rabindra Behera'
      },
      khasraCount: 140,
      affectedFamiliesCount: 92
    },
    {
      _id: 'proj_008_patna',
      id: 'proj_008_patna',
      projectId: 'PRJ-MOHUA-PMRC-008',
      projectCode: 'PRJ-MOHUA-PMRC-008',
      projectName: 'Patna Metro Rail Transit Corridor Phase-1 (Danapur-Khemnichak)',
      title: 'Patna Metro Rail Transit Corridor Phase-1 (Danapur-Khemnichak)',
      projectType: 'Urban Development',
      sector: 'Urban Development',
      description: 'Mass rapid transit corridor spanning 14.5 km with underground & elevated stations to modernize metropolitan public transit.',
      ministry: 'Ministry of Housing and Urban Affairs (MoHUA)',
      implementingAgency: 'Patna Metro Rail Corporation (PMRC)',
      state: 'Bihar',
      district: 'Patna',
      tehsil: 'Phulwari Sharif',
      village: 'Mithapur',
      statesCovered: ['Bihar'],
      districtsCovered: ['Patna'],
      tehsilsCovered: ['Phulwari Sharif'],
      villagesCovered: ['Mithapur', 'Anisabad', 'Danapur Cantonment'],
      totalProjectArea: 110.0,
      requiredLandArea: 85.0,
      targetAcquisitionAreaHectares: 85.0,
      acquiredLandArea: 45.0,
      acquiredAreaHectares: 45.0,
      estimatedBudgetCrores: 4200,
      estimatedCostInCrores: 4200,
      compensationDisbursedCrores: 340.0,
      currentStage: 'SECTION_11_NOTIFIED',
      status: 'Active Acquisition',
      startDate: new Date('2024-01-20'),
      expectedCompletionDate: new Date('2027-12-31'),
      assignedOfficers: {
        calaOfficerName: 'Shri Alok Ranjan, BAS',
        districtOfficerName: 'Dr. Chandrashekhar Singh, IAS',
        surveyorOfficerName: 'Shri Bindeshwar Paswan'
      },
      khasraCount: 95,
      affectedFamiliesCount: 68
    },
    {
      _id: 'proj_009_thar',
      id: 'proj_009_thar',
      projectId: 'PRJ-MOP-THAR-009',
      projectCode: 'PRJ-MOP-THAR-009',
      projectName: 'Thar Green Energy Evacuation & Power Transmission Corridor',
      title: 'Thar Green Energy Evacuation & Power Transmission Corridor',
      projectType: 'Renewable Energy',
      sector: 'Renewable Energy',
      description: '765 kV double circuit interstate transmission corridor evacuating 5 GW clean solar electricity to northern industrial centers.',
      ministry: 'Ministry of Power',
      implementingAgency: 'Power Grid Corporation of India (POWERGRID)',
      state: 'Rajasthan',
      district: 'Jaisalmer',
      tehsil: 'Fatehgarh',
      village: 'Devikot',
      statesCovered: ['Rajasthan'],
      districtsCovered: ['Jaisalmer'],
      tehsilsCovered: ['Fatehgarh'],
      villagesCovered: ['Devikot', 'Sangad', 'Bhojasar'],
      totalProjectArea: 450.0,
      requiredLandArea: 380.0,
      targetAcquisitionAreaHectares: 380.0,
      acquiredLandArea: 190.0,
      acquiredAreaHectares: 190.0,
      estimatedBudgetCrores: 1850,
      estimatedCostInCrores: 1850,
      compensationDisbursedCrores: 160.0,
      currentStage: 'SIA_APPROVED',
      status: 'Active Acquisition',
      startDate: new Date('2024-04-01'),
      expectedCompletionDate: new Date('2026-10-31'),
      assignedOfficers: {
        calaOfficerName: 'Shri Bhanwar Lal Meena, RAS',
        districtOfficerName: 'Shri Ashish Gupta, IAS',
        surveyorOfficerName: 'Shri Mularam Bishnoi'
      },
      khasraCount: 160,
      affectedFamiliesCount: 52
    },
    {
      _id: 'proj_010_kenbetwa',
      id: 'proj_010_kenbetwa',
      projectId: 'PRJ-NWDA-KBIC-010',
      projectCode: 'PRJ-NWDA-KBIC-010',
      projectName: 'Ken-Betwa River Interlinking Feeder Canal Infrastructure',
      title: 'Ken-Betwa River Interlinking Feeder Canal Infrastructure',
      projectType: 'Irrigation',
      sector: 'Irrigation',
      description: 'Inter-basin water transfer canal carrying surplus water from the Ken basin to water-deficit Bundelkhand districts of MP and UP.',
      ministry: 'Ministry of Jal Shakti',
      implementingAgency: 'National Water Development Agency (NWDA)',
      state: 'Madhya Pradesh',
      district: 'Chhatarpur',
      tehsil: 'Bijawar',
      village: 'Dhaudan',
      statesCovered: ['Madhya Pradesh'],
      districtsCovered: ['Chhatarpur'],
      tehsilsCovered: ['Bijawar'],
      villagesCovered: ['Dhaudan', 'Khandeha', 'Palka'],
      totalProjectArea: 900.0,
      requiredLandArea: 710.0,
      targetAcquisitionAreaHectares: 710.0,
      acquiredLandArea: 80.0,
      acquiredAreaHectares: 80.0,
      estimatedBudgetCrores: 6400,
      estimatedCostInCrores: 6400,
      compensationDisbursedCrores: 88.0,
      currentStage: 'PROPOSAL_SUBMITTED',
      status: 'Under Verification',
      startDate: new Date('2024-06-15'),
      expectedCompletionDate: new Date('2028-03-31'),
      assignedOfficers: {
        calaOfficerName: 'Shri Sanjeev Sahu, MP State Service',
        districtOfficerName: 'Smt. Pratibha Pal, IAS',
        surveyorOfficerName: 'Shri Hiralal Patel'
      },
      khasraCount: 310,
      affectedFamiliesCount: 180
    }
  ];

  // 3. PROPOSALS (Corresponding to projects across all 7 workflow states)
  const proposals = [
    {
      _id: 'prop_001',
      id: 'prop_001',
      proposalId: 'PROP-2024-001',
      projectId: 'PRJ-NHAI-DME-001',
      projectName: 'Delhi-Mumbai Expressway (Vadodara-JNPT Spur Package 14)',
      projectType: 'Highway',
      sponsoringAgency: 'National Highways Authority of India (NHAI)',
      state: 'Maharashtra',
      district: 'Thane',
      tehsil: 'Bhiwandi',
      villages: ['Padgha', 'Khadavali', 'Borivali-T'],
      requiredAreaHectares: 320.5,
      estimatedCostInCrores: 3450,
      justification: 'Critical port connectivity corridor linking JNPT terminal to the National Capital Region with 40% reduction in transit logistics cost.',
      status: 'Acquisition Initiated',
      submittedDate: new Date('2024-01-18'),
      submittedBy: { name: 'Er. Manoj Verma', designation: 'Project Director, NHAI' },
      districtVerification: {
        verifiedBy: 'Shri Ashok Kumar Meena, IAS (DM, Thane)',
        verificationDate: new Date('2024-02-05'),
        landRecordsStatus: '100% Khasra records verified with 7/12 RoR registers',
        fieldInspectionDone: true,
        remarks: 'Alignment approved. Social impact assessment study cleared.',
        passed: true
      },
      stateReview: {
        reviewedBy: 'Shri Vikramaditya Jadhav, IAS (Divisional Commissioner)',
        reviewDate: new Date('2024-02-20'),
        siaFeasibilityStatus: 'Cleared under Section 4(1) provisions',
        remarks: 'State cabinet sanction granted.',
        passed: true
      },
      centralReview: {
        reviewedBy: 'Smt. Ananya Sen, IRTS (Joint Secretary, MoRTH)',
        reviewDate: new Date('2024-03-05'),
        cabinetSanctionRef: 'CCEA-NHAI-EXP-2024/09',
        sanctionedBudgetInCrores: 3450,
        remarks: 'National sanction issued. CALA authorized to proceed under Section 11.',
        passed: true
      },
      approvedDate: new Date('2024-03-05'),
      acquisitionInitiatedDate: new Date('2024-03-10')
    },
    {
      _id: 'prop_002',
      id: 'prop_002',
      proposalId: 'PROP-2024-002',
      projectId: 'PRJ-MOR-WDFC-002',
      projectCode: 'PRJ-MOR-WDFC-002',
      projectName: 'Western Dedicated Freight Corridor (Surat-Palanpur Section)',
      projectType: 'Railway',
      sponsoringAgency: 'DFCCIL / Indian Railways',
      state: 'Gujarat',
      district: 'Surat',
      tehsil: 'Choryasi',
      villages: ['Sachin', 'Udhna'],
      requiredAreaHectares: 210.0,
      estimatedCostInCrores: 4890,
      justification: 'Dedicated double-stack freight track to segregate passenger and cargo train paths.',
      status: 'Acquisition Initiated',
      submittedDate: new Date('2023-08-10'),
      submittedBy: { name: 'Shri K. R. Nambiar', designation: 'General Manager, DFCCIL' },
      districtVerification: {
        verifiedBy: 'Dr. Ayush Sharma, IAS (DM, Surat)',
        verificationDate: new Date('2023-08-25'),
        landRecordsStatus: 'AnyRoR portal verification completed',
        fieldInspectionDone: true,
        remarks: 'Minimal forest diversion required.',
        passed: true
      },
      stateReview: {
        reviewedBy: 'Revenue Department, Govt of Gujarat',
        reviewDate: new Date('2023-09-12'),
        passed: true
      },
      centralReview: {
        reviewedBy: 'Railway Board & MoR',
        reviewDate: new Date('2023-09-28'),
        cabinetSanctionRef: 'RLY-DFC-W-2023-88',
        passed: true
      },
      approvedDate: new Date('2023-09-28'),
      acquisitionInitiatedDate: new Date('2023-10-05')
    },
    {
      _id: 'prop_003',
      id: 'prop_003',
      proposalId: 'PROP-2024-003',
      projectId: 'PRJ-UPEIDA-GNGA-003',
      projectName: 'Ganga Expressway Greenfield Corridor Phase-II',
      projectType: 'Highway',
      sponsoringAgency: 'UPEIDA',
      state: 'Uttar Pradesh',
      district: 'Prayagraj',
      tehsil: 'Soraon',
      villages: ['Mandawa', 'Mauaima'],
      requiredAreaHectares: 480.0,
      estimatedCostInCrores: 5200,
      justification: 'Expedite east-west industrial logistics transit in Eastern Uttar Pradesh.',
      status: 'Central Review',
      submittedDate: new Date('2024-03-05'),
      submittedBy: { name: 'Shri Durgesh Sharma', designation: 'Executive Engineer, UPEIDA' },
      districtVerification: {
        verifiedBy: 'Shri Manish Verma, IAS',
        verificationDate: new Date('2024-03-22'),
        landRecordsStatus: 'Bhulekh UP verified',
        fieldInspectionDone: true,
        passed: true
      },
      stateReview: {
        reviewedBy: 'Principal Secretary (Infrastructure), UP',
        reviewDate: new Date('2024-04-10'),
        passed: true
      },
      centralReview: {
        reviewedBy: 'MoRTH Project Review Committee',
        remarks: 'Under final CCEA ministerial financial appraisal.',
        passed: false
      }
    },
    {
      _id: 'prop_004',
      id: 'prop_004',
      proposalId: 'PROP-2024-004',
      projectId: 'PRJ-NICDC-CBIC-004',
      projectName: 'Chennai-Bengaluru Industrial Corridor (Ponneri Node)',
      projectType: 'Industrial Corridor',
      sponsoringAgency: 'NICDC / TIDCO',
      state: 'Tamil Nadu',
      district: 'Tiruvallur',
      tehsil: 'Ponneri',
      villages: ['Kattupalli'],
      requiredAreaHectares: 350.0,
      estimatedCostInCrores: 2850,
      justification: 'Integrated manufacturing hub with proximity to Kattupalli port for semiconductor and automotive export.',
      status: 'Approved',
      submittedDate: new Date('2023-11-20'),
      submittedBy: { name: 'Thiru S. Rajagopalan', designation: 'Director, TIDCO' },
      districtVerification: {
        verifiedBy: 'Dr. T. Prabhu, IAS',
        verificationDate: new Date('2023-12-10'),
        landRecordsStatus: 'Tamil Nilam e-Services records verified',
        passed: true
      },
      stateReview: {
        reviewedBy: 'Industries Dept, Govt of Tamil Nadu',
        reviewDate: new Date('2024-01-05'),
        passed: true
      },
      centralReview: {
        reviewedBy: 'DPIIT National Industrial Steering Committee',
        reviewDate: new Date('2024-01-25'),
        cabinetSanctionRef: 'DPIIT-NICDC-CBIC-04',
        passed: true
      },
      approvedDate: new Date('2024-01-25')
    },
    {
      _id: 'prop_005',
      id: 'prop_005',
      proposalId: 'PROP-2024-005',
      projectId: 'PRJ-KRN-UKP3-005',
      projectName: 'Upper Krishna Irrigation & Canal Project Stage-III',
      projectType: 'Irrigation',
      sponsoringAgency: 'KBJNL',
      state: 'Karnataka',
      district: 'Bagalkote',
      tehsil: 'Bilagi',
      villages: ['Galgali', 'Sunag'],
      requiredAreaHectares: 620.0,
      estimatedCostInCrores: 3100,
      justification: 'Water security and irrigation for 5.3 lakh hectares drought-prone farmland.',
      status: 'State Review',
      submittedDate: new Date('2024-02-15'),
      submittedBy: { name: 'Er. Mallikarjun B.', designation: 'Chief Engineer, KBJNL' },
      districtVerification: {
        verifiedBy: 'Shri Janardhan R., IAS',
        verificationDate: new Date('2024-03-08'),
        landRecordsStatus: 'Bhoomi Karnataka records cross-checked',
        passed: true
      }
    },
    {
      _id: 'prop_006',
      id: 'prop_006',
      proposalId: 'PROP-2024-006',
      projectId: 'PRJ-MNRE-KRNL-006',
      projectName: 'Kurnool Ultra Mega Hybrid Solar & Wind Renewable Energy Park',
      projectType: 'Renewable Energy',
      sponsoringAgency: 'SECI / AP Transco',
      state: 'Andhra Pradesh',
      district: 'Kurnool',
      tehsil: 'Orvakal',
      villages: ['Gani', 'Sakunala'],
      requiredAreaHectares: 540.0,
      estimatedCostInCrores: 2100,
      justification: 'Accelerate national 500 GW non-fossil renewable capacity commitment.',
      status: 'Acquisition Initiated',
      submittedDate: new Date('2023-05-20'),
      submittedBy: { name: 'Shri Ch. Venkat Rao', designation: 'DGM, SECI' },
      districtVerification: { verifiedBy: 'Dr. G. Srijana, IAS', verificationDate: new Date('2023-06-10'), passed: true },
      stateReview: { reviewedBy: 'Energy Dept, AP', reviewDate: new Date('2023-06-25'), passed: true },
      centralReview: { reviewedBy: 'MNRE Board', reviewDate: new Date('2023-07-15'), passed: true },
      approvedDate: new Date('2023-07-15')
    },
    {
      _id: 'prop_007',
      id: 'prop_007',
      proposalId: 'PROP-2024-007',
      projectId: 'PRJ-MOD-DRDO-007',
      projectName: 'National Strategic Naval Radar & Coastal Defense Facility',
      projectType: 'Defense',
      sponsoringAgency: 'DRDO',
      state: 'Odisha',
      district: 'Balasore',
      tehsil: 'Chandipur',
      villages: ['Balaramgadi'],
      requiredAreaHectares: 290.0,
      estimatedCostInCrores: 1950,
      justification: 'Strategic national security defense and maritime telemetry infrastructure.',
      status: 'Acquisition Initiated',
      submittedDate: new Date('2023-04-15'),
      submittedBy: { name: 'Col. P. K. Mohanty', designation: 'Estate Officer, DRDO' },
      districtVerification: { verifiedBy: 'Shri D. B. Sahoo, IAS', verificationDate: new Date('2023-04-28'), passed: true },
      stateReview: { reviewedBy: 'Revenue & DM Dept, Odisha', reviewDate: new Date('2023-05-15'), passed: true },
      centralReview: { reviewedBy: 'Cabinet Committee on Security (CCS)', reviewDate: new Date('2023-06-02'), passed: true },
      approvedDate: new Date('2023-06-02')
    },
    {
      _id: 'prop_008',
      id: 'prop_008',
      proposalId: 'PROP-2024-008',
      projectId: 'PRJ-MOHUA-PMRC-008',
      projectName: 'Patna Metro Rail Transit Corridor Phase-1 (Danapur-Khemnichak)',
      projectType: 'Urban Development',
      sponsoringAgency: 'PMRC / Urban Development Dept',
      state: 'Bihar',
      district: 'Patna',
      tehsil: 'Phulwari Sharif',
      villages: ['Mithapur'],
      requiredAreaHectares: 85.0,
      estimatedCostInCrores: 4200,
      justification: 'High-density urban mass mobility corridor connecting transit hubs and railway terminus.',
      status: 'District Verification',
      submittedDate: new Date('2024-01-25'),
      submittedBy: { name: 'Shri R. K. Jha', designation: 'Director (Projects), PMRC' },
      districtVerification: {
        verifiedBy: 'Dr. Chandrashekhar Singh, IAS',
        landRecordsStatus: 'Biharbhumi verification ongoing for commercial properties.',
        passed: false
      }
    },
    {
      _id: 'prop_009',
      id: 'prop_009',
      proposalId: 'PROP-2024-009',
      projectId: 'PRJ-MOP-THAR-009',
      projectName: 'Thar Green Energy Evacuation & Power Transmission Corridor',
      projectType: 'Renewable Energy',
      sponsoringAgency: 'POWERGRID',
      state: 'Rajasthan',
      district: 'Jaisalmer',
      tehsil: 'Fatehgarh',
      villages: ['Devikot'],
      requiredAreaHectares: 380.0,
      estimatedCostInCrores: 1850,
      justification: 'Critical 765 kV transmission towers connecting 5 GW western solar plants to the national grid.',
      status: 'District Verification',
      submittedDate: new Date('2024-04-10'),
      submittedBy: { name: 'Shri Vikram Rathore', designation: 'Chief Manager, POWERGRID' },
      districtVerification: {
        verifiedBy: 'Shri Ashish Gupta, IAS',
        landRecordsStatus: 'Apna Khata Rajasthan records matching.',
        passed: false
      }
    },
    {
      _id: 'prop_010',
      id: 'prop_010',
      proposalId: 'PROP-2024-010',
      projectId: 'PRJ-NWDA-KBIC-010',
      projectName: 'Ken-Betwa River Interlinking Feeder Canal Infrastructure',
      projectType: 'Irrigation',
      sponsoringAgency: 'NWDA',
      state: 'Madhya Pradesh',
      district: 'Chhatarpur',
      tehsil: 'Bijawar',
      villages: ['Dhaudan'],
      requiredAreaHectares: 710.0,
      estimatedCostInCrores: 6400,
      justification: 'First project under the National Perspective Plan for interlinking of rivers to tackle perennial water shortage in Bundelkhand.',
      status: 'Submitted',
      submittedDate: new Date('2024-06-20'),
      submittedBy: { name: 'Er. O. P. Tiwari', designation: 'Superintending Engineer, NWDA' }
    },
    {
      _id: 'prop_011',
      id: 'prop_011',
      proposalId: 'PROP-2024-011',
      projectId: 'PRJ-NHAI-SNG-011',
      projectName: 'Sangam Greenfield Bypass & Logistics Access Ring Road',
      projectType: 'Highway',
      sponsoringAgency: 'National Highways Authority of India (NHAI)',
      state: 'Uttar Pradesh',
      district: 'Prayagraj',
      tehsil: 'Phulpur',
      villages: ['Jhusi', 'Sahson'],
      requiredAreaHectares: 175.5,
      estimatedCostInCrores: 1420,
      justification: 'Peripheral decongestion bypass for Mahakumbh corridor connectivity under PM GatiShakti.',
      status: 'Draft',
      submittedBy: { name: 'Shri A. K. Shukla', designation: 'Project Manager, NHAI PIU' }
    },
    {
      _id: 'prop_012',
      id: 'prop_012',
      proposalId: 'PROP-2024-012',
      projectId: 'PRJ-SIDC-ECO-012',
      projectName: 'Aravalli Eco-Industrial Freight & Warehousing Enclave',
      projectType: 'Industrial Corridor',
      sponsoringAgency: 'Haryana State Industrial Development Corp',
      state: 'Haryana',
      district: 'Gurugram',
      tehsil: 'Sohna',
      villages: ['Rozka Meo'],
      requiredAreaHectares: 240.0,
      estimatedCostInCrores: 2150,
      justification: 'Logistics warehousing park along Western Peripheral Expressway.',
      status: 'Rejected',
      submittedDate: new Date('2024-01-10'),
      submittedBy: { name: 'Shri Sandeep Hooda', designation: 'General Manager, HSIIDC' },
      districtVerification: {
        verifiedBy: 'Shri Nishant Kumar Yadav, IAS (DC, Gurugram)',
        verificationDate: new Date('2024-01-28'),
        landRecordsStatus: 'Sub-judice ecological buffer zone restriction under Aravalli Notification.',
        fieldInspectionDone: true,
        remarks: 'Land overlaps notified Eco-Sensitive Zone and Natural Conservation Zone (NCZ).',
        passed: false
      },
      rejectionReason: 'Ecological buffer violation under Supreme Court Aravalli protection directives; non-permissible zone under Regional Plan 2021.'
    }
  ];

  // 4. 32 LAND PARCELS WITH REALISTIC KHASRA NUMBERS, OWNERS & GEOJSON BOUNDARIES
  const landParcels = [
    // DME Project (Thane, Maharashtra)
    {
      _id: 'pcl_001',
      id: 'pcl_001',
      projectId: 'PRJ-NHAI-DME-001',
      khasraNumber: '42/1',
      state: 'Maharashtra',
      district: 'Thane',
      tehsil: 'Bhiwandi',
      village: 'Padgha',
      landCategory: 'Private Agricultural (Irrigated)',
      totalAreaHectares: 2.85,
      acquiredAreaHectares: 2.85,
      circleRatePerHectare: 4500000,
      marketValuePerHectare: 5400000,
      acquisitionStatus: 'Award Determined',
      owners: [{ name: 'Shri Tukaram Balaram Patil', sharePercentage: 100, aadhaarMasked: 'XXXX-XXXX-3829', bankDetails: { accountNumber: '30981123456', ifscCode: 'SBIN0001234', bankName: 'SBI Bhiwandi' }, contactPhone: '+91 98220 11221' }],
      geometry: { type: 'Polygon', coordinates: [[[73.125, 19.342], [73.128, 19.342], [73.128, 19.345], [73.125, 19.345], [73.125, 19.342]]] },
      gisAttributes: { centroid: { lat: 19.3435, lng: 73.1265 }, treesCount: 14, structuresCount: 1, jointMeasurementSurveyDone: true }
    },
    {
      _id: 'pcl_002',
      id: 'pcl_002',
      projectId: 'PRJ-NHAI-DME-001',
      khasraNumber: '42/2',
      state: 'Maharashtra',
      district: 'Thane',
      tehsil: 'Bhiwandi',
      village: 'Padgha',
      landCategory: 'Private Agricultural (Irrigated)',
      totalAreaHectares: 3.40,
      acquiredAreaHectares: 3.40,
      circleRatePerHectare: 4500000,
      marketValuePerHectare: 5400000,
      acquisitionStatus: 'Disbursed',
      owners: [{ name: 'Smt. Shantabai Kashinath Mhatre', sharePercentage: 100, aadhaarMasked: 'XXXX-XXXX-9124', bankDetails: { accountNumber: '20194857291', ifscCode: 'MAHB0000452', bankName: 'Bank of Maharashtra' }, contactPhone: '+91 98220 44552' }],
      geometry: { type: 'Polygon', coordinates: [[[73.128, 19.342], [73.131, 19.342], [73.131, 19.345], [73.128, 19.345], [73.128, 19.342]]] },
      gisAttributes: { centroid: { lat: 19.3435, lng: 73.1295 }, treesCount: 8, structuresCount: 0, jointMeasurementSurveyDone: true }
    },
    {
      _id: 'pcl_003',
      id: 'pcl_003',
      projectId: 'PRJ-NHAI-DME-001',
      khasraNumber: '45/3',
      state: 'Maharashtra',
      district: 'Thane',
      tehsil: 'Bhiwandi',
      village: 'Padgha',
      landCategory: 'Private Agricultural (Unirrigated)',
      totalAreaHectares: 1.95,
      acquiredAreaHectares: 1.95,
      circleRatePerHectare: 3800000,
      marketValuePerHectare: 4560000,
      acquisitionStatus: 'Possession Transferred',
      owners: [{ name: 'Shri Eknath Dharma Bhoir', sharePercentage: 50, aadhaarMasked: 'XXXX-XXXX-5521' }, { name: 'Shri Vilas Dharma Bhoir', sharePercentage: 50, aadhaarMasked: 'XXXX-XXXX-5522' }],
      geometry: { type: 'Polygon', coordinates: [[[73.131, 19.342], [73.134, 19.342], [73.134, 19.345], [73.131, 19.345], [73.131, 19.342]]] },
      gisAttributes: { centroid: { lat: 19.3435, lng: 73.1325 }, treesCount: 5, structuresCount: 0, jointMeasurementSurveyDone: true }
    },
    {
      _id: 'pcl_004',
      id: 'pcl_004',
      projectId: 'PRJ-NHAI-DME-001',
      khasraNumber: '89/A',
      state: 'Maharashtra',
      district: 'Thane',
      tehsil: 'Bhiwandi',
      village: 'Khadavali',
      landCategory: 'Private Non-Agricultural / Commercial',
      totalAreaHectares: 0.85,
      acquiredAreaHectares: 0.85,
      circleRatePerHectare: 7500000,
      marketValuePerHectare: 9200000,
      acquisitionStatus: 'Award Determined',
      owners: [{ name: 'Shri Arvind J. Shah', sharePercentage: 100, aadhaarMasked: 'XXXX-XXXX-4411' }],
      geometry: { type: 'Polygon', coordinates: [[[73.140, 19.350], [73.143, 19.350], [73.143, 19.353], [73.140, 19.353], [73.140, 19.350]]] },
      gisAttributes: { centroid: { lat: 19.3515, lng: 73.1415 }, treesCount: 0, structuresCount: 2, jointMeasurementSurveyDone: true }
    },
    // WDFC Project (Surat, Gujarat)
    {
      _id: 'pcl_005',
      id: 'pcl_005',
      projectId: 'PRJ-MOR-WDFC-002',
      khasraNumber: '108/3',
      state: 'Gujarat',
      district: 'Surat',
      tehsil: 'Choryasi',
      village: 'Sachin',
      landCategory: 'Private Agricultural (Irrigated)',
      totalAreaHectares: 4.20,
      acquiredAreaHectares: 4.20,
      circleRatePerHectare: 5200000,
      marketValuePerHectare: 6800000,
      acquisitionStatus: 'Possession Transferred',
      owners: [{ name: 'Shri Pravinbhai Chaganbhai Patel', sharePercentage: 100, aadhaarMasked: 'XXXX-XXXX-6612' }],
      geometry: { type: 'Polygon', coordinates: [[[72.880, 21.080], [72.884, 21.080], [72.884, 21.084], [72.880, 21.084], [72.880, 21.080]]] },
      gisAttributes: { centroid: { lat: 21.082, lng: 72.882 }, treesCount: 12, structuresCount: 0, jointMeasurementSurveyDone: true }
    },
    {
      _id: 'pcl_006',
      id: 'pcl_006',
      projectId: 'PRJ-MOR-WDFC-002',
      khasraNumber: '112/1',
      state: 'Gujarat',
      district: 'Surat',
      tehsil: 'Choryasi',
      village: 'Sachin',
      landCategory: 'Private Agricultural (Irrigated)',
      totalAreaHectares: 2.75,
      acquiredAreaHectares: 2.75,
      circleRatePerHectare: 5200000,
      marketValuePerHectare: 6800000,
      acquisitionStatus: 'Possession Transferred',
      owners: [{ name: 'Shri Jayeshkumar V. Desai', sharePercentage: 100, aadhaarMasked: 'XXXX-XXXX-9901' }],
      geometry: { type: 'Polygon', coordinates: [[[72.884, 21.080], [72.888, 21.080], [72.888, 21.084], [72.884, 21.084], [72.884, 21.080]]] },
      gisAttributes: { centroid: { lat: 21.082, lng: 72.886 }, treesCount: 6, structuresCount: 0, jointMeasurementSurveyDone: true }
    },
    // Ganga Expressway (Prayagraj, UP)
    {
      _id: 'pcl_007',
      id: 'pcl_007',
      projectId: 'PRJ-UPEIDA-GNGA-003',
      khasraNumber: '215',
      state: 'Uttar Pradesh',
      district: 'Prayagraj',
      tehsil: 'Soraon',
      village: 'Mandawa',
      landCategory: 'Private Agricultural (Irrigated)',
      totalAreaHectares: 3.10,
      acquiredAreaHectares: 3.10,
      circleRatePerHectare: 3200000,
      marketValuePerHectare: 4000000,
      acquisitionStatus: 'Sec 11 Notified',
      owners: [{ name: 'Shri Ram Dulare Yadav', sharePercentage: 100, aadhaarMasked: 'XXXX-XXXX-1102' }],
      geometry: { type: 'Polygon', coordinates: [[[81.820, 25.560], [81.824, 25.560], [81.824, 25.564], [81.820, 25.564], [81.820, 25.560]]] },
      gisAttributes: { centroid: { lat: 25.562, lng: 81.822 }, treesCount: 15, structuresCount: 1, jointMeasurementSurveyDone: true }
    },
    {
      _id: 'pcl_008',
      id: 'pcl_008',
      projectId: 'PRJ-UPEIDA-GNGA-003',
      khasraNumber: '216/A',
      state: 'Uttar Pradesh',
      district: 'Prayagraj',
      tehsil: 'Soraon',
      village: 'Mandawa',
      landCategory: 'Private Agricultural (Irrigated)',
      totalAreaHectares: 2.45,
      acquiredAreaHectares: 2.45,
      circleRatePerHectare: 3200000,
      marketValuePerHectare: 4000000,
      acquisitionStatus: 'Sec 11 Notified',
      owners: [{ name: 'Shri Shiv Prasad Tiwari', sharePercentage: 100, aadhaarMasked: 'XXXX-XXXX-4499' }],
      geometry: { type: 'Polygon', coordinates: [[[81.824, 25.560], [81.828, 25.560], [81.828, 25.564], [81.824, 25.564], [81.824, 25.560]]] },
      gisAttributes: { centroid: { lat: 25.562, lng: 81.826 }, treesCount: 8, structuresCount: 0, jointMeasurementSurveyDone: true }
    },
    // Chennai-Bengaluru Corridor (Ponneri, TN)
    {
      _id: 'pcl_009',
      id: 'pcl_009',
      projectId: 'PRJ-NICDC-CBIC-004',
      khasraNumber: '312/1B',
      state: 'Tamil Nadu',
      district: 'Tiruvallur',
      tehsil: 'Ponneri',
      village: 'Kattupalli',
      landCategory: 'Private Agricultural (Unirrigated)',
      totalAreaHectares: 5.60,
      acquiredAreaHectares: 5.60,
      circleRatePerHectare: 4100000,
      marketValuePerHectare: 5300000,
      acquisitionStatus: 'Award Determined',
      owners: [{ name: 'Thiru M. Subramanian', sharePercentage: 100, aadhaarMasked: 'XXXX-XXXX-8811' }],
      geometry: { type: 'Polygon', coordinates: [[[80.320, 13.310], [80.325, 13.310], [80.325, 13.315], [80.320, 13.315], [80.320, 13.310]]] },
      gisAttributes: { centroid: { lat: 13.3125, lng: 80.3225 }, treesCount: 4, structuresCount: 0, jointMeasurementSurveyDone: true }
    },
    {
      _id: 'pcl_010',
      id: 'pcl_010',
      projectId: 'PRJ-NICDC-CBIC-004',
      khasraNumber: '312/2',
      state: 'Tamil Nadu',
      district: 'Tiruvallur',
      tehsil: 'Ponneri',
      village: 'Kattupalli',
      landCategory: 'Private Agricultural (Unirrigated)',
      totalAreaHectares: 4.10,
      acquiredAreaHectares: 4.10,
      circleRatePerHectare: 4100000,
      marketValuePerHectare: 5300000,
      acquisitionStatus: 'Award Determined',
      owners: [{ name: 'Tmt. Lakshmi Ammal', sharePercentage: 100, aadhaarMasked: 'XXXX-XXXX-7722' }],
      geometry: { type: 'Polygon', coordinates: [[[80.325, 13.310], [80.330, 13.310], [80.330, 13.315], [80.325, 13.315], [80.325, 13.310]]] },
      gisAttributes: { centroid: { lat: 13.3125, lng: 80.3275 }, treesCount: 7, structuresCount: 0, jointMeasurementSurveyDone: true }
    },
    // Upper Krishna Irrigation (Bagalkote, Karnataka)
    {
      _id: 'pcl_011',
      id: 'pcl_011',
      projectId: 'PRJ-KRN-UKP3-005',
      khasraNumber: '78/2',
      state: 'Karnataka',
      district: 'Bagalkote',
      tehsil: 'Bilagi',
      village: 'Galgali',
      landCategory: 'Private Agricultural (Irrigated)',
      totalAreaHectares: 6.20,
      acquiredAreaHectares: 6.20,
      circleRatePerHectare: 2800000,
      marketValuePerHectare: 3500000,
      acquisitionStatus: 'Sec 11 Notified',
      owners: [{ name: 'Shri Basavaraj Gouda', sharePercentage: 100, aadhaarMasked: 'XXXX-XXXX-3344' }],
      geometry: { type: 'Polygon', coordinates: [[[75.480, 16.320], [75.485, 16.320], [75.485, 16.325], [75.480, 16.325], [75.480, 16.320]]] },
      gisAttributes: { centroid: { lat: 16.3225, lng: 75.4825 }, treesCount: 18, structuresCount: 1, jointMeasurementSurveyDone: true }
    },
    // Kurnool Solar (AP)
    {
      _id: 'pcl_012',
      id: 'pcl_012',
      projectId: 'PRJ-MNRE-KRNL-006',
      khasraNumber: '142',
      state: 'Andhra Pradesh',
      district: 'Kurnool',
      tehsil: 'Orvakal',
      village: 'Gani',
      landCategory: 'Private Agricultural (Unirrigated)',
      totalAreaHectares: 8.50,
      acquiredAreaHectares: 8.50,
      circleRatePerHectare: 1800000,
      marketValuePerHectare: 2400000,
      acquisitionStatus: 'Possession Transferred',
      owners: [{ name: 'Shri K. Pedda Reddy', sharePercentage: 100, aadhaarMasked: 'XXXX-XXXX-9922' }],
      geometry: { type: 'Polygon', coordinates: [[[78.210, 15.680], [78.216, 15.680], [78.216, 15.686], [78.210, 15.686], [78.210, 15.680]]] },
      gisAttributes: { centroid: { lat: 15.683, lng: 78.213 }, treesCount: 2, structuresCount: 0, jointMeasurementSurveyDone: true }
    },
    // Defense Naval Facility (Balasore, Odisha)
    {
      _id: 'pcl_013',
      id: 'pcl_013',
      projectId: 'PRJ-MOD-DRDO-007',
      khasraNumber: '88/1',
      state: 'Odisha',
      district: 'Balasore',
      tehsil: 'Chandipur',
      village: 'Balaramgadi',
      landCategory: 'Private Agricultural (Unirrigated)',
      totalAreaHectares: 4.80,
      acquiredAreaHectares: 4.80,
      circleRatePerHectare: 2400000,
      marketValuePerHectare: 3100000,
      acquisitionStatus: 'Possession Transferred',
      owners: [{ name: 'Shri Jagannath Das', sharePercentage: 100, aadhaarMasked: 'XXXX-XXXX-1122' }],
      geometry: { type: 'Polygon', coordinates: [[[87.010, 21.450], [87.015, 21.450], [87.015, 21.455], [87.010, 21.455], [87.010, 21.450]]] },
      gisAttributes: { centroid: { lat: 21.4525, lng: 87.0125 }, treesCount: 11, structuresCount: 0, jointMeasurementSurveyDone: true }
    },
    // Patna Metro (Bihar)
    {
      _id: 'pcl_014',
      id: 'pcl_014',
      projectId: 'PRJ-MOHUA-PMRC-008',
      khasraNumber: '44',
      state: 'Bihar',
      district: 'Patna',
      tehsil: 'Phulwari Sharif',
      village: 'Mithapur',
      landCategory: 'Private Non-Agricultural / Commercial',
      totalAreaHectares: 0.65,
      acquiredAreaHectares: 0.65,
      circleRatePerHectare: 12000000,
      marketValuePerHectare: 16000000,
      acquisitionStatus: 'Sec 11 Notified',
      owners: [{ name: 'Shri Shambhu Nath Prasad', sharePercentage: 100, aadhaarMasked: 'XXXX-XXXX-4545' }],
      geometry: { type: 'Polygon', coordinates: [[[85.120, 25.590], [85.123, 25.590], [85.123, 25.593], [85.120, 25.593], [85.120, 25.590]]] },
      gisAttributes: { centroid: { lat: 25.5915, lng: 85.1215 }, treesCount: 0, structuresCount: 3, jointMeasurementSurveyDone: true }
    },
    // Thar Green Energy (Rajasthan)
    {
      _id: 'pcl_015',
      id: 'pcl_015',
      projectId: 'PRJ-MOP-THAR-009',
      khasraNumber: '502',
      state: 'Rajasthan',
      district: 'Jaisalmer',
      tehsil: 'Fatehgarh',
      village: 'Devikot',
      landCategory: 'Private Agricultural (Unirrigated)',
      totalAreaHectares: 12.00,
      acquiredAreaHectares: 12.00,
      circleRatePerHectare: 1100000,
      marketValuePerHectare: 1400000,
      acquisitionStatus: 'Proposed',
      owners: [{ name: 'Shri Rawal Singh Bhati', sharePercentage: 100, aadhaarMasked: 'XXXX-XXXX-9900' }],
      geometry: { type: 'Polygon', coordinates: [[[71.180, 26.650], [71.190, 26.650], [71.190, 26.660], [71.180, 26.660], [71.180, 26.650]]] },
      gisAttributes: { centroid: { lat: 26.655, lng: 71.185 }, treesCount: 0, structuresCount: 0, jointMeasurementSurveyDone: false }
    },
    // Ken-Betwa Canal (MP)
    {
      _id: 'pcl_016',
      id: 'pcl_016',
      projectId: 'PRJ-NWDA-KBIC-010',
      khasraNumber: '19',
      state: 'Madhya Pradesh',
      district: 'Chhatarpur',
      tehsil: 'Bijawar',
      village: 'Dhaudan',
      landCategory: 'Government / Gaon Sabha',
      totalAreaHectares: 15.50,
      acquiredAreaHectares: 15.50,
      circleRatePerHectare: 1500000,
      marketValuePerHectare: 1900000,
      acquisitionStatus: 'Proposed',
      owners: [{ name: 'Gaon Sabha Dhaudan / MP Revenue Dept', sharePercentage: 100, aadhaarMasked: 'GOVT-RECORD-001' }],
      geometry: { type: 'Polygon', coordinates: [[[79.820, 24.620], [79.830, 24.620], [79.830, 24.630], [79.820, 24.630], [79.820, 24.620]]] },
      gisAttributes: { centroid: { lat: 24.625, lng: 79.825 }, treesCount: 45, structuresCount: 0, jointMeasurementSurveyDone: false }
    }
  ];

  // Add more parcels up to 32 covering all 10 states and all 8 statutory statuses
  const statutoryStatuses = [
    'Proposed',
    'Under Verification',
    'Notification Issued',
    'Awarded',
    'Compensation Paid',
    'Possession Taken',
    'R&R Pending',
    'Completed'
  ];

  const projectCoords = {
    'Maharashtra': { lat: 19.345, lng: 73.125 },
    'Gujarat': { lat: 21.082, lng: 72.882 },
    'Uttar Pradesh': { lat: 25.562, lng: 81.822 },
    'Tamil Nadu': { lat: 13.312, lng: 80.322 },
    'Karnataka': { lat: 16.322, lng: 75.482 },
    'Andhra Pradesh': { lat: 15.683, lng: 78.213 },
    'Odisha': { lat: 21.452, lng: 87.012 },
    'Bihar': { lat: 25.591, lng: 85.121 },
    'Rajasthan': { lat: 26.655, lng: 71.185 },
    'Madhya Pradesh': { lat: 24.625, lng: 79.825 }
  };

  for (let i = 17; i <= 32; i++) {
    const projIndex = (i % 10);
    const p = projects[projIndex];
    const status = statutoryStatuses[(i - 17) % statutoryStatuses.length];
    const baseCoords = projectCoords[p.state] || { lat: 20.5937, lng: 78.9629 };
    const offsetLat = ((i % 5) * 0.004) + 0.002;
    const offsetLng = ((i % 4) * 0.004) + 0.002;
    const parcelLat = baseCoords.lat + offsetLat;
    const parcelLng = baseCoords.lng + offsetLng;
    const area = Number((1.5 + ((i % 7) * 0.45)).toFixed(2));
    const circleRate = 3500000 + ((i % 5) * 250000);
    const marketValue = circleRate * 1.2;

    landParcels.push({
      _id: `pcl_0${i}`,
      id: `pcl_0${i}`,
      parcelId: `PCL-${p.state.substring(0, 2).toUpperCase()}-${p.district.substring(0, 3).toUpperCase()}-0${i}`,
      projectId: p.projectId,
      projectName: p.projectName,
      surveyNumber: `${60 + i}/${(i % 4) + 1}`,
      khasraNumber: `${60 + i}/${(i % 4) + 1}`,
      state: p.state,
      district: p.district,
      tehsil: p.tehsil,
      village: p.village,
      landCategory: i % 2 === 0 ? 'Private Agricultural (Irrigated)' : 'Private Agricultural (Unirrigated)',
      area,
      totalAreaHectares: area,
      acquiredAreaHectares: area,
      circleRatePerHectare: circleRate,
      marketValuePerHectare: marketValue,
      acquisitionStatus: status,
      latitude: parcelLat,
      longitude: parcelLng,
      owners: [{
        name: `Shri Landholder ${i} (${p.state})`,
        sharePercentage: 100,
        aadhaarMasked: `XXXX-XXXX-${2000 + i}`,
        bankDetails: { accountNumber: `9988112200${i}`, ifscCode: 'SBIN0001234', bankName: 'State Bank of India' },
        contactPhone: `+91 98110 ${10000 + i}`
      }],
      affectedFamilyReference: {
        familyId: `PAF-${p.state.substring(0, 2).toUpperCase()}-${p.district.substring(0, 3).toUpperCase()}-0${i}`,
        familyHeadName: `Shri Landholder ${i}`,
        vulnerabilityCategory: i % 3 === 0 ? 'Marginal Farmer / BPL' : 'General Farmer',
        aadhaarMasked: `XXXX-XXXX-${2000 + i}`
      },
      compensation: {
        amount: Math.round(area * marketValue * 2.12),
        status: ['Compensation Paid', 'Possession Taken', 'Completed'].includes(status) ? 'Paid' : (status === 'Awarded' ? 'Assessed' : 'Pending'),
        disbursedDate: ['Compensation Paid', 'Possession Taken', 'Completed'].includes(status) ? new Date('2024-04-01') : null,
        utrNumber: ['Compensation Paid', 'Possession Taken', 'Completed'].includes(status) ? `PFMS-DBT-2024-00${i}` : null
      },
      possession: {
        status: ['Possession Taken', 'Completed'].includes(status) ? 'Possession Taken' : 'Not Taken',
        certificateNumber: ['Possession Taken', 'Completed'].includes(status) ? `FORM-11-${p.district.substring(0, 3).toUpperCase()}-2024-0${i}` : null,
        possessionDate: ['Possession Taken', 'Completed'].includes(status) ? new Date('2024-04-15') : null
      },
      rrStatus: {
        status: status === 'Completed' ? 'Settled' : (status === 'R&R Pending' ? 'Pending Allotment' : 'Not Applicable'),
        schemeName: 'RFCTLARR Second Schedule Scheme',
        houseAllotted: status === 'Completed',
        subsistenceGrantPaid: ['Compensation Paid', 'Possession Taken', 'Completed'].includes(status)
      },
      geometry: {
        type: 'Polygon',
        coordinates: [[
          [parcelLng, parcelLat],
          [parcelLng + 0.003, parcelLat],
          [parcelLng + 0.003, parcelLat + 0.003],
          [parcelLng, parcelLat + 0.003],
          [parcelLng, parcelLat]
        ]]
      },
      gisAttributes: {
        centroid: { lat: parcelLat + 0.0015, lng: parcelLng + 0.0015 },
        treesCount: 3 + (i % 6),
        structuresCount: i % 5 === 0 ? 1 : 0,
        jointMeasurementSurveyDone: true
      }
    });
  }

  // 5. 16 STATUTORY GAZETTE NOTIFICATIONS
  const notifications = [
    {
      _id: 'notif_001',
      id: 'notif_001',
      notificationNumber: 'S.O. 1245(E)',
      projectId: 'PRJ-NHAI-DME-001',
      section: 'Section 11 Preliminary',
      gazetteNumber: 'CG-DL-E-15032024-245102',
      gazetteDate: new Date('2024-03-15'),
      publicationDate: new Date('2024-03-16'),
      statutoryLapseDate: new Date('2025-03-15'), // 12-month clock under Sec 19
      affectedVillages: ['Padgha', 'Khadavali', 'Borivali-T'],
      totalAreaHectares: 320.5,
      totalKhasrasCovered: 148,
      status: 'Completed',
      issuedBy: 'Shri Suresh K. Patil, CALA',
      documentUrl: '/documents/gazette_sec11_dme.pdf',
      description: 'Preliminary notification declaring public purpose acquisition for access-controlled expressway.'
    },
    {
      _id: 'notif_002',
      id: 'notif_002',
      notificationNumber: 'S.O. 3892(E)',
      projectId: 'PRJ-NHAI-DME-001',
      section: 'Section 19 Declaration',
      gazetteNumber: 'CG-DL-E-20102024-258901',
      gazetteDate: new Date('2024-10-20'),
      publicationDate: new Date('2024-10-21'),
      affectedVillages: ['Padgha', 'Khadavali', 'Borivali-T'],
      totalAreaHectares: 320.5,
      totalKhasrasCovered: 148,
      status: 'Completed',
      issuedBy: 'Revenue & Forest Department, Govt of Maharashtra',
      documentUrl: '/documents/gazette_sec19_dme.pdf',
      description: 'Statutory Declaration under Section 19(1) of RFCTLARR Act 2013 after disposal of Section 15 objections.'
    },
    {
      _id: 'notif_003',
      id: 'notif_003',
      notificationNumber: 'S.O. 882(E)',
      projectId: 'PRJ-MOR-WDFC-002',
      section: 'Section 11 Preliminary',
      gazetteNumber: 'CG-GJ-E-01102023-119283',
      gazetteDate: new Date('2023-10-01'),
      publicationDate: new Date('2023-10-02'),
      affectedVillages: ['Sachin', 'Udhna'],
      totalAreaHectares: 210.0,
      totalKhasrasCovered: 112,
      status: 'Completed',
      issuedBy: 'Competent Authority, DFCCIL Surat',
      documentUrl: '/documents/gazette_sec11_wdfc.pdf',
      description: 'Preliminary notice for railway freight corridor acquisition.'
    },
    {
      _id: 'notif_004',
      id: 'notif_004',
      notificationNumber: 'S.O. 1824(E)',
      projectId: 'PRJ-MOR-WDFC-002',
      section: 'Section 19 Declaration',
      gazetteNumber: 'CG-GJ-E-15042024-130491',
      gazetteDate: new Date('2024-04-15'),
      publicationDate: new Date('2024-04-16'),
      affectedVillages: ['Sachin', 'Udhna'],
      totalAreaHectares: 210.0,
      totalKhasrasCovered: 112,
      status: 'Completed',
      issuedBy: 'Govt of Gujarat Revenue Dept',
      documentUrl: '/documents/gazette_sec19_wdfc.pdf',
      description: 'Final declaration of land acquisition for freight corridor.'
    },
    {
      _id: 'notif_005',
      id: 'notif_005',
      notificationNumber: 'S.O. 2210(E)',
      projectId: 'PRJ-UPEIDA-GNGA-003',
      section: 'Section 11 Preliminary',
      gazetteNumber: 'CG-UP-E-12052024-331002',
      gazetteDate: new Date('2024-05-12'),
      publicationDate: new Date('2024-05-13'),
      statutoryLapseDate: new Date('2025-05-12'),
      affectedVillages: ['Mandawa', 'Mauaima'],
      totalAreaHectares: 480.0,
      totalKhasrasCovered: 220,
      status: 'Objections Under Review',
      issuedBy: 'SLAO / CALA Prayagraj',
      documentUrl: '/documents/gazette_sec11_ganga.pdf',
      description: 'Section 11 Gazette published. 60-day public objection period active.'
    },
    {
      _id: 'notif_006',
      id: 'notif_006',
      notificationNumber: 'S.O. 945(E)',
      projectId: 'PRJ-NICDC-CBIC-004',
      section: 'Section 11 Preliminary',
      gazetteNumber: 'CG-TN-E-28022024-441092',
      gazetteDate: new Date('2024-02-28'),
      publicationDate: new Date('2024-03-01'),
      affectedVillages: ['Kattupalli'],
      totalAreaHectares: 350.0,
      totalKhasrasCovered: 175,
      status: 'Completed',
      issuedBy: 'District Revenue Officer, Tiruvallur',
      documentUrl: '/documents/gazette_sec11_cbic.pdf',
      description: 'Section 11 notification for industrial corridor node.'
    },
    {
      _id: 'notif_007',
      id: 'notif_007',
      notificationNumber: 'S.O. 2940(E)',
      projectId: 'PRJ-NICDC-CBIC-004',
      section: 'Section 19 Declaration',
      gazetteNumber: 'CG-TN-E-15092024-450192',
      gazetteDate: new Date('2024-09-15'),
      publicationDate: new Date('2024-09-16'),
      affectedVillages: ['Kattupalli'],
      totalAreaHectares: 350.0,
      totalKhasrasCovered: 175,
      status: 'Gazette Published',
      issuedBy: 'Industries Dept, Govt of Tamil Nadu',
      documentUrl: '/documents/gazette_sec19_cbic.pdf',
      description: 'Declaration under Section 19(1) for industrial park.'
    },
    {
      _id: 'notif_008',
      id: 'notif_008',
      notificationNumber: 'S.O. 1105(E)',
      projectId: 'PRJ-KRN-UKP3-005',
      section: 'Section 11 Preliminary',
      gazetteNumber: 'CG-KA-E-10042024-661001',
      gazetteDate: new Date('2024-04-10'),
      publicationDate: new Date('2024-04-11'),
      affectedVillages: ['Galgali', 'Sunag'],
      totalAreaHectares: 620.0,
      totalKhasrasCovered: 260,
      status: 'Objections Under Review',
      issuedBy: 'Special Land Acquisition Officer, UKP Bilagi',
      documentUrl: '/documents/gazette_sec11_ukp.pdf',
      description: 'Preliminary gazette notification for canal alignment.'
    },
    {
      _id: 'notif_009',
      id: 'notif_009',
      notificationNumber: 'S.O. 450(E)',
      projectId: 'PRJ-MNRE-KRNL-006',
      section: 'Section 11 Preliminary',
      gazetteNumber: 'CG-AP-E-12082023-771092',
      gazetteDate: new Date('2023-08-12'),
      publicationDate: new Date('2023-08-13'),
      affectedVillages: ['Gani', 'Sakunala'],
      totalAreaHectares: 540.0,
      totalKhasrasCovered: 190,
      status: 'Completed',
      issuedBy: 'Revenue Divisional Officer, Kurnool',
      documentUrl: '/documents/gazette_sec11_kurnool.pdf',
      description: 'Notification for solar park land acquisition.'
    },
    {
      _id: 'notif_010',
      id: 'notif_010',
      notificationNumber: 'S.O. 1350(E)',
      projectId: 'PRJ-MNRE-KRNL-006',
      section: 'Section 19 Declaration',
      gazetteNumber: 'CG-AP-E-20022024-780192',
      gazetteDate: new Date('2024-02-20'),
      publicationDate: new Date('2024-02-21'),
      affectedVillages: ['Gani', 'Sakunala'],
      totalAreaHectares: 540.0,
      totalKhasrasCovered: 190,
      status: 'Completed',
      issuedBy: 'Govt of Andhra Pradesh',
      documentUrl: '/documents/gazette_sec19_kurnool.pdf',
      description: 'Final declaration for clean energy park.'
    },
    {
      _id: 'notif_011',
      id: 'notif_011',
      notificationNumber: 'S.O. 310(E)',
      projectId: 'PRJ-MOD-DRDO-007',
      section: 'Section 11 Preliminary',
      gazetteNumber: 'CG-OD-E-05072023-881001',
      gazetteDate: new Date('2023-07-05'),
      publicationDate: new Date('2023-07-06'),
      affectedVillages: ['Balaramgadi'],
      totalAreaHectares: 290.0,
      totalKhasrasCovered: 140,
      status: 'Completed',
      issuedBy: 'Collector, Balasore',
      documentUrl: '/documents/gazette_sec11_defense.pdf',
      description: 'Preliminary notification for strategic defense test facility.'
    },
    {
      _id: 'notif_012',
      id: 'notif_012',
      notificationNumber: 'S.O. 980(E)',
      projectId: 'PRJ-MOD-DRDO-007',
      section: 'Section 19 Declaration',
      gazetteNumber: 'CG-OD-E-15122023-890123',
      gazetteDate: new Date('2023-12-15'),
      publicationDate: new Date('2023-12-16'),
      affectedVillages: ['Balaramgadi'],
      totalAreaHectares: 290.0,
      totalKhasrasCovered: 140,
      status: 'Completed',
      issuedBy: 'Govt of Odisha Revenue Dept',
      documentUrl: '/documents/gazette_sec19_defense.pdf',
      description: 'Declaration under Section 19 for defense facility.'
    },
    {
      _id: 'notif_013',
      id: 'notif_013',
      notificationNumber: 'S.O. 1402(E)',
      projectId: 'PRJ-MOHUA-PMRC-008',
      section: 'Section 11 Preliminary',
      gazetteNumber: 'CG-BR-E-10022024-991001',
      gazetteDate: new Date('2024-02-10'),
      publicationDate: new Date('2024-02-11'),
      statutoryLapseDate: new Date('2025-02-10'),
      affectedVillages: ['Mithapur'],
      totalAreaHectares: 85.0,
      totalKhasrasCovered: 95,
      status: 'Gazette Published',
      issuedBy: 'District Magistrate, Patna',
      documentUrl: '/documents/gazette_sec11_metro.pdf',
      description: 'Section 11 notification for metro station depots and tracks.'
    },
    {
      _id: 'notif_014',
      id: 'notif_014',
      notificationNumber: 'S.O. 1890(E)',
      projectId: 'PRJ-MOP-THAR-009',
      section: 'Section 4 SIA',
      gazetteNumber: 'CG-RJ-E-25042024-110022',
      gazetteDate: new Date('2024-04-25'),
      publicationDate: new Date('2024-04-26'),
      affectedVillages: ['Devikot', 'Sangad'],
      totalAreaHectares: 380.0,
      totalKhasrasCovered: 160,
      status: 'Completed',
      issuedBy: 'Collector & District Magistrate, Jaisalmer',
      documentUrl: '/documents/gazette_sec4_thar.pdf',
      description: 'Social Impact Assessment notification for transmission line.'
    },
    {
      _id: 'notif_015',
      id: 'notif_015',
      notificationNumber: 'S.O. 2280(E)',
      projectId: 'PRJ-NWDA-KBIC-010',
      section: 'Section 4 SIA',
      gazetteNumber: 'CG-MP-E-01072024-221001',
      gazetteDate: new Date('2024-07-01'),
      publicationDate: new Date('2024-07-02'),
      affectedVillages: ['Dhaudan'],
      totalAreaHectares: 710.0,
      totalKhasrasCovered: 310,
      status: 'Draft',
      issuedBy: 'Revenue Dept, Govt of MP',
      documentUrl: '/documents/gazette_sec4_kenbetwa.pdf',
      description: 'Preliminary SIA study order under Section 4.'
    },
    {
      _id: 'notif_016',
      id: 'notif_016',
      notificationNumber: 'S.O. 3120(E)',
      projectId: 'PRJ-NHAI-DME-001',
      section: 'Section 21 Public Notice',
      gazetteNumber: 'CG-DL-E-02112024-260192',
      gazetteDate: new Date('2024-11-02'),
      publicationDate: new Date('2024-11-03'),
      affectedVillages: ['Padgha'],
      totalAreaHectares: 45.0,
      totalKhasrasCovered: 24,
      status: 'Completed',
      issuedBy: 'Shri Suresh K. Patil, CALA',
      documentUrl: '/documents/gazette_sec21_dme.pdf',
      description: 'Public notice inviting claims for compensation under Section 21.'
    }
  ];

  // 6. 12 SECTION 23/30 AWARDS WITH 100% SOLATIUM & 12% INTEREST
  const awards = [
    {
      _id: 'awd_001',
      id: 'awd_001',
      awardNumber: 'AWD-THN-SEC23-2024-001',
      projectId: 'PRJ-NHAI-DME-001',
      section: 'Section 23 & 30',
      awardDate: new Date('2024-11-15'),
      passedBy: 'Shri Suresh K. Patil, Competent Authority & Deputy Collector',
      approvedByCollector: 'Shri Ashok Kumar Meena, IAS (Collector, Thane)',
      khasraNumbersCovered: ['42/1', '42/2', '45/3'],
      totalAreaHectares: 8.20,
      assessedLandMarketValue: 44280000,
      structuresValue: 1850000,
      treesAndCropsValue: 420000,
      totalBaseCompensation: 46550000,
      solatiumPercentage: 100,
      solatiumAmount: 46550000,
      additionalInterestRate: 12,
      additionalInterestAmount: 3724000,
      totalAwardAmount: 96824000,
      status: 'Approved by Collector',
      digitalSignatureHash: 'SHA256:4a8b792e9f123c8e41a90c237894d01b',
      awardDocumentUrl: '/documents/award_sec23_dme_pkg14.pdf',
      remarks: 'Full 100% Solatium computed per RFCTLARR Sec 30(1) + 12% statutory interest under Sec 30(3).'
    },
    {
      _id: 'awd_002',
      id: 'awd_002',
      awardNumber: 'AWD-THN-SEC23-2024-002',
      projectId: 'PRJ-NHAI-DME-001',
      section: 'Section 23 & 30',
      awardDate: new Date('2024-11-20'),
      passedBy: 'Shri Suresh K. Patil, CALA',
      approvedByCollector: 'Shri Ashok Kumar Meena, IAS',
      khasraNumbersCovered: ['89/A'],
      totalAreaHectares: 0.85,
      assessedLandMarketValue: 7820000,
      structuresValue: 3200000,
      treesAndCropsValue: 0,
      totalBaseCompensation: 11020000,
      solatiumPercentage: 100,
      solatiumAmount: 11020000,
      additionalInterestRate: 12,
      additionalInterestAmount: 881600,
      totalAwardAmount: 22921600,
      status: 'Approved by Collector',
      digitalSignatureHash: 'SHA256:7b9c123d4e5f6a7b8c9d0e1f2a3b4c5d',
      awardDocumentUrl: '/documents/award_sec23_dme_comm.pdf'
    },
    {
      _id: 'awd_003',
      id: 'awd_003',
      awardNumber: 'AWD-SRT-SEC23-2024-001',
      projectId: 'PRJ-MOR-WDFC-002',
      section: 'Section 23 & 30',
      awardDate: new Date('2024-05-10'),
      passedBy: 'Shri H. R. Patel, GAS (CALA, DFCCIL)',
      approvedByCollector: 'Dr. Ayush Sharma, IAS (Collector, Surat)',
      khasraNumbersCovered: ['108/3', '112/1'],
      totalAreaHectares: 6.95,
      assessedLandMarketValue: 47260000,
      structuresValue: 0,
      treesAndCropsValue: 580000,
      totalBaseCompensation: 47840000,
      solatiumPercentage: 100,
      solatiumAmount: 47840000,
      additionalInterestRate: 12,
      additionalInterestAmount: 3827200,
      totalAwardAmount: 99507200,
      status: 'Fully Settled',
      digitalSignatureHash: 'SHA256:1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d',
      awardDocumentUrl: '/documents/award_sec23_wdfc.pdf'
    },
    {
      _id: 'awd_004',
      id: 'awd_004',
      awardNumber: 'AWD-TVL-SEC23-2024-001',
      projectId: 'PRJ-NICDC-CBIC-004',
      section: 'Section 23 & 30',
      awardDate: new Date('2024-10-05'),
      passedBy: 'Tmt. K. Vasanthi, DRO Tiruvallur',
      approvedByCollector: 'Dr. T. Prabhu, IAS',
      khasraNumbersCovered: ['312/1B', '312/2'],
      totalAreaHectares: 9.70,
      assessedLandMarketValue: 51410000,
      structuresValue: 950000,
      treesAndCropsValue: 340000,
      totalBaseCompensation: 52700000,
      solatiumPercentage: 100,
      solatiumAmount: 52700000,
      additionalInterestRate: 12,
      additionalInterestAmount: 4216000,
      totalAwardAmount: 109616000,
      status: 'Approved by Collector',
      digitalSignatureHash: 'SHA256:9c8b7a6d5e4f3a2b1c0d9e8f7a6b5c4d',
      awardDocumentUrl: '/documents/award_sec23_cbic.pdf'
    },
    {
      _id: 'awd_005',
      id: 'awd_005',
      awardNumber: 'AWD-KNL-SEC23-2024-001',
      projectId: 'PRJ-MNRE-KRNL-006',
      section: 'Section 23 & 30',
      awardDate: new Date('2024-03-12'),
      passedBy: 'Shri P. Srinivasulu, RDO Kurnool',
      approvedByCollector: 'Dr. G. Srijana, IAS',
      khasraNumbersCovered: ['142'],
      totalAreaHectares: 8.50,
      assessedLandMarketValue: 20400000,
      structuresValue: 0,
      treesAndCropsValue: 120000,
      totalBaseCompensation: 20520000,
      solatiumPercentage: 100,
      solatiumAmount: 20520000,
      additionalInterestRate: 12,
      additionalInterestAmount: 1641600,
      totalAwardAmount: 42681600,
      status: 'Fully Settled',
      digitalSignatureHash: 'SHA256:5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c',
      awardDocumentUrl: '/documents/award_sec23_solar.pdf'
    },
    {
      _id: 'awd_006',
      id: 'awd_006',
      awardNumber: 'AWD-BLS-SEC23-2024-001',
      projectId: 'PRJ-MOD-DRDO-007',
      section: 'Section 23 & 30',
      awardDate: new Date('2024-01-18'),
      passedBy: 'Shri D. K. Jena, OAS',
      approvedByCollector: 'Shri D. B. Sahoo, IAS',
      khasraNumbersCovered: ['88/1'],
      totalAreaHectares: 4.80,
      assessedLandMarketValue: 14880000,
      structuresValue: 450000,
      treesAndCropsValue: 180000,
      totalBaseCompensation: 15510000,
      solatiumPercentage: 100,
      solatiumAmount: 15510000,
      additionalInterestRate: 12,
      additionalInterestAmount: 1240800,
      totalAwardAmount: 32260800,
      status: 'Fully Settled',
      digitalSignatureHash: 'SHA256:8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d',
      awardDocumentUrl: '/documents/award_sec23_drdo.pdf'
    }
  ];

  // Add more awards up to 12
  for (let i = 7; i <= 12; i++) {
    const projIndex = (i % 10);
    const p = projects[projIndex];
    awards.push({
      _id: `awd_00${i}`,
      id: `awd_00${i}`,
      awardNumber: `AWD-${p.district.substring(0, 3).toUpperCase()}-2024-00${i}`,
      projectId: p.projectId,
      section: 'Section 23 & 30',
      awardDate: new Date('2024-08-10'),
      passedBy: `CALA & Deputy Collector, ${p.district}`,
      approvedByCollector: `District Magistrate, ${p.district}`,
      khasraNumbersCovered: [`${i * 10}/1`, `${i * 10}/2`],
      totalAreaHectares: Number((2.5 + (i * 0.4)).toFixed(2)),
      assessedLandMarketValue: 15000000 + (i * 1200000),
      structuresValue: 500000,
      treesAndCropsValue: 200000,
      totalBaseCompensation: 15700000 + (i * 1200000),
      solatiumPercentage: 100,
      solatiumAmount: 15700000 + (i * 1200000),
      additionalInterestRate: 12,
      additionalInterestAmount: Math.round((15700000 + (i * 1200000)) * 0.08),
      totalAwardAmount: Math.round((15700000 + (i * 1200000)) * 2.08),
      status: 'Approved by Collector',
      digitalSignatureHash: `SHA256:gen_award_${i}_hash_${Date.now().toString(36)}`
    });
  }

  // 7. 24 BENEFICIARY COMPENSATION & PFMS DBT RECORDS
  const compensations = [
    {
      _id: 'cmp_001',
      id: 'cmp_001',
      compensationId: 'CMP-2024-001',
      projectId: 'PRJ-NHAI-DME-001',
      awardNumber: 'AWD-THN-SEC23-2024-001',
      khasraNumber: '42/1',
      village: 'Padgha',
      beneficiaryName: 'Shri Tukaram Balaram Patil',
      beneficiaryAadhaarMasked: 'XXXX-XXXX-3829',
      beneficiaryPan: 'ABCDE1234F',
      bankAccountNumber: '30981123456',
      bankIfsc: 'SBIN0001234',
      bankName: 'State Bank of India',
      acquiredAreaHectares: 2.85,
      circleRatePerHectare: 4500000,
      multiplicationFactor: 1.2,
      marketValueAssessed: 15390000,
      assetsValue: 850000,
      totalBaseCompensation: 16240000,
      solatiumAmount: 16240000,
      additionalInterest: 1299200,
      totalCompensationPayable: 33779200,
      paymentStatus: 'DBT Disbursed',
      pfmsReferenceNumber: 'PFMS-2024-MH-0091823',
      dbtTransactionId: 'DBT/RBI/2024/991204812',
      disbursementDate: new Date('2024-11-28')
    },
    {
      _id: 'cmp_002',
      id: 'cmp_002',
      compensationId: 'CMP-2024-002',
      projectId: 'PRJ-NHAI-DME-001',
      awardNumber: 'AWD-THN-SEC23-2024-001',
      khasraNumber: '42/2',
      village: 'Padgha',
      beneficiaryName: 'Smt. Shantabai Kashinath Mhatre',
      beneficiaryAadhaarMasked: 'XXXX-XXXX-9124',
      beneficiaryPan: 'FGHIJ5678K',
      bankAccountNumber: '20194857291',
      bankIfsc: 'MAHB0000452',
      bankName: 'Bank of Maharashtra',
      acquiredAreaHectares: 3.40,
      circleRatePerHectare: 4500000,
      multiplicationFactor: 1.2,
      marketValueAssessed: 18360000,
      assetsValue: 400000,
      totalBaseCompensation: 18760000,
      solatiumAmount: 18760000,
      additionalInterest: 1500800,
      totalCompensationPayable: 39020800,
      paymentStatus: 'DBT Disbursed',
      pfmsReferenceNumber: 'PFMS-2024-MH-0091824',
      dbtTransactionId: 'DBT/RBI/2024/991204813',
      disbursementDate: new Date('2024-11-28')
    },
    {
      _id: 'cmp_003',
      id: 'cmp_003',
      compensationId: 'CMP-2024-003',
      projectId: 'PRJ-NHAI-DME-001',
      awardNumber: 'AWD-THN-SEC23-2024-002',
      khasraNumber: '89/A',
      village: 'Khadavali',
      beneficiaryName: 'Shri Arvind J. Shah',
      beneficiaryAadhaarMasked: 'XXXX-XXXX-4411',
      bankAccountNumber: '10928374650',
      bankIfsc: 'HDFC0001002',
      bankName: 'HDFC Bank',
      acquiredAreaHectares: 0.85,
      circleRatePerHectare: 7500000,
      multiplicationFactor: 1.0,
      marketValueAssessed: 7820000,
      assetsValue: 3200000,
      totalBaseCompensation: 11020000,
      solatiumAmount: 11020000,
      additionalInterest: 881600,
      totalCompensationPayable: 22921600,
      paymentStatus: 'PFMS Batch Generated',
      pfmsReferenceNumber: 'PFMS-2024-MH-0092101'
    }
  ];

  // Add more compensations up to 24
  for (let i = 4; i <= 24; i++) {
    const projIndex = (i % 10);
    const p = projects[projIndex];
    compensations.push({
      _id: `cmp_0${i}`,
      id: `cmp_0${i}`,
      compensationId: `CMP-2024-0${i}`,
      projectId: p.projectId,
      awardNumber: `AWD-${p.district.substring(0, 3).toUpperCase()}-2024-001`,
      khasraNumber: `${30 + i}/${(i % 3) + 1}`,
      village: p.village,
      beneficiaryName: `Farmer Beneficiary ${i}`,
      beneficiaryAadhaarMasked: `XXXX-XXXX-${3000 + i}`,
      bankAccountNumber: `5010098273${i}`,
      bankIfsc: 'SBIN0002451',
      bankName: 'State Bank of India',
      acquiredAreaHectares: Number((1.2 + (i * 0.1)).toFixed(2)),
      circleRatePerHectare: 3500000,
      multiplicationFactor: 1.2,
      marketValueAssessed: Math.round((1.2 + (i * 0.1)) * 3500000 * 1.2),
      assetsValue: 200000,
      totalBaseCompensation: Math.round((1.2 + (i * 0.1)) * 3500000 * 1.2) + 200000,
      solatiumAmount: Math.round((1.2 + (i * 0.1)) * 3500000 * 1.2) + 200000,
      additionalInterest: Math.round(((1.2 + (i * 0.1)) * 3500000 * 1.2) * 0.08),
      totalCompensationPayable: Math.round(((1.2 + (i * 0.1)) * 3500000 * 1.2 + 200000) * 2.08),
      paymentStatus: i % 3 === 0 ? 'PFMS Batch Generated' : 'DBT Disbursed',
      pfmsReferenceNumber: `PFMS-2024-${p.state.substring(0, 2).toUpperCase()}-00${8000 + i}`,
      dbtTransactionId: i % 3 !== 0 ? `DBT/RBI/2024/991823${i}` : undefined,
      disbursementDate: i % 3 !== 0 ? new Date('2024-11-20') : undefined
    });
  }

  // 8. 22 PROJECT AFFECTED FAMILIES (PAFS) WITH VULNERABILITY FLAGS
  const affectedFamilies = [
    {
      _id: 'fam_001',
      id: 'fam_001',
      familyRegistrationId: 'PAF-MH-THN-001',
      projectId: 'PRJ-NHAI-DME-001',
      familyHeadName: 'Shri Tukaram Balaram Patil',
      vulnerabilityCategory: 'General',
      membersCount: 5,
      village: 'Padgha',
      district: 'Thane',
      khasraNumber: '42/1',
      lossCategory: 'Only Agricultural Land Acquired',
      entitlements: {
        houseAllocated: false,
        resettlementSiteName: 'Padgha R&R Enclave',
        subsistenceGrantAmount: 36000,
        subsistencePaid: true,
        transportationAllowance: 50000,
        transportationPaid: true,
        oneTimeResettlementAllowance: 50000,
        resettlementAllowancePaid: true,
        rehabilitationLivelihoodOption: 'One-time Lump Sum Grant (₹5,00,000)',
        livelihoodSettled: true
      },
      status: 'FULLY_REHABILITATED'
    },
    {
      _id: 'fam_002',
      id: 'fam_002',
      familyRegistrationId: 'PAF-MH-THN-002',
      projectId: 'PRJ-NHAI-DME-001',
      familyHeadName: 'Smt. Shantabai Kashinath Mhatre',
      vulnerabilityCategory: 'Below Poverty Line (BPL)',
      membersCount: 4,
      village: 'Padgha',
      district: 'Thane',
      khasraNumber: '42/2',
      lossCategory: 'Homestead & Agricultural Land Displaced',
      entitlements: {
        houseAllocated: true,
        resettlementSiteName: 'PM Awas R&R Colony Sector 2, Bhiwandi',
        subsistenceGrantAmount: 36000,
        subsistencePaid: true,
        transportationAllowance: 50000,
        transportationPaid: true,
        oneTimeResettlementAllowance: 50000,
        resettlementAllowancePaid: true,
        rehabilitationLivelihoodOption: 'One-time Lump Sum Grant (₹5,00,000)',
        livelihoodSettled: true
      },
      status: 'RESETTLEMENT_IN_PROGRESS'
    },
    {
      _id: 'fam_003',
      id: 'fam_003',
      familyRegistrationId: 'PAF-MH-THN-003',
      projectId: 'PRJ-NHAI-DME-001',
      familyHeadName: 'Shri Eknath Dharma Bhoir',
      vulnerabilityCategory: 'Scheduled Tribe (ST)',
      membersCount: 6,
      village: 'Padgha',
      district: 'Thane',
      khasraNumber: '45/3',
      lossCategory: 'Homestead & Agricultural Land Displaced',
      entitlements: {
        houseAllocated: true,
        resettlementSiteName: 'PM Awas Tribal R&R Enclave',
        subsistenceGrantAmount: 50000, // Additional ST entitlement
        subsistencePaid: true,
        transportationAllowance: 50000,
        transportationPaid: true,
        oneTimeResettlementAllowance: 50000,
        resettlementAllowancePaid: true,
        rehabilitationLivelihoodOption: 'Monthly Annuity (₹2,000/mo for 20 yrs)',
        livelihoodSettled: true
      },
      status: 'FULLY_REHABILITATED'
    }
  ];

  // Add more PAFs up to 22
  for (let i = 4; i <= 22; i++) {
    const projIndex = (i % 10);
    const p = projects[projIndex];
    const vulnTypes = [
      'Scheduled Tribe (ST)',
      'Scheduled Caste (SC)',
      'Below Poverty Line (BPL)',
      'Marginal Farmer (< 1 Ha)',
      'Agricultural Labourer / Tenant',
      'General'
    ];
    affectedFamilies.push({
      _id: `fam_0${i}`,
      id: `fam_0${i}`,
      familyRegistrationId: `PAF-${p.state.substring(0, 2).toUpperCase()}-${p.district.substring(0, 3).toUpperCase()}-0${i}`,
      projectId: p.projectId,
      familyHeadName: `Family Head ${i} (${p.village})`,
      vulnerabilityCategory: vulnTypes[i % vulnTypes.length],
      membersCount: 3 + (i % 4),
      village: p.village,
      district: p.district,
      khasraNumber: `${20 + i}/1`,
      lossCategory: i % 2 === 0 ? 'Homestead & Agricultural Land Displaced' : 'Only Agricultural Land Acquired',
      entitlements: {
        houseAllocated: i % 2 === 0,
        resettlementSiteName: `${p.district} Model R&R Colony`,
        subsistenceGrantAmount: 36000,
        subsistencePaid: i > 10,
        transportationAllowance: 50000,
        transportationPaid: i > 10,
        oneTimeResettlementAllowance: 50000,
        resettlementAllowancePaid: i > 10,
        rehabilitationLivelihoodOption: 'One-time Lump Sum Grant (₹5,00,000)',
        livelihoodSettled: i > 12
      },
      status: i > 15 ? 'SURVEYED' : (i > 8 ? 'R_AND_R_APPROVED' : 'FULLY_REHABILITATED')
    });
  }

  // 9. 10 POSSESSION RECORDS (Section 38 Handover & Form 11)
  const possessions = [
    {
      _id: 'pos_001',
      id: 'pos_001',
      possessionId: 'POS-2024-001',
      possessionCertificateNumber: 'FORM-11-THN-2024-042',
      projectId: 'PRJ-NHAI-DME-001',
      section38NoticeDate: new Date('2024-11-22'),
      physicalPossessionDate: new Date('2024-12-05'),
      handoverToAgencyDate: new Date('2024-12-10'),
      khasraNumbersCovered: ['42/1', '42/2', '45/3'],
      totalAreaHandedOverHectares: 8.20,
      encroachmentsCleared: true,
      encumbranceFreeCertificateIssued: true,
      status: 'Handed Over to Implementing Agency',
      officerInCharge: 'Shri Suresh K. Patil (CALA & Deputy Collector)',
      agencyRepresentative: 'Er. Manoj Verma (Project Director, NHAI)',
      form11CertificateUrl: '/documents/form11_possession_dme.pdf',
      remarks: 'Full uninhibited possession handed over after 100% solatium DBT crediting.'
    },
    {
      _id: 'pos_002',
      id: 'pos_002',
      possessionId: 'POS-2024-002',
      possessionCertificateNumber: 'FORM-11-SRT-2024-018',
      projectId: 'PRJ-MOR-WDFC-002',
      section38NoticeDate: new Date('2024-05-15'),
      physicalPossessionDate: new Date('2024-06-01'),
      handoverToAgencyDate: new Date('2024-06-05'),
      khasraNumbersCovered: ['108/3', '112/1'],
      totalAreaHandedOverHectares: 6.95,
      encroachmentsCleared: true,
      encumbranceFreeCertificateIssued: true,
      status: 'Handed Over to Implementing Agency',
      officerInCharge: 'Shri H. R. Patel, GAS',
      agencyRepresentative: 'Chief Project Manager, DFCCIL Surat',
      form11CertificateUrl: '/documents/form11_possession_wdfc.pdf'
    },
    {
      _id: 'pos_003',
      id: 'pos_003',
      possessionId: 'POS-2024-003',
      possessionCertificateNumber: 'FORM-11-KNL-2024-012',
      projectId: 'PRJ-MNRE-KRNL-006',
      section38NoticeDate: new Date('2024-03-15'),
      physicalPossessionDate: new Date('2024-03-30'),
      handoverToAgencyDate: new Date('2024-04-05'),
      khasraNumbersCovered: ['142'],
      totalAreaHandedOverHectares: 8.50,
      encroachmentsCleared: true,
      encumbranceFreeCertificateIssued: true,
      status: 'Handed Over to Implementing Agency',
      officerInCharge: 'Shri P. Srinivasulu, RDO',
      agencyRepresentative: 'General Manager, SECI',
      form11CertificateUrl: '/documents/form11_possession_solar.pdf'
    },
    {
      _id: 'pos_004',
      id: 'pos_004',
      possessionId: 'POS-2024-004',
      possessionCertificateNumber: 'FORM-11-BLS-2024-009',
      projectId: 'PRJ-MOD-DRDO-007',
      section38NoticeDate: new Date('2024-01-25'),
      physicalPossessionDate: new Date('2024-02-10'),
      handoverToAgencyDate: new Date('2024-02-15'),
      khasraNumbersCovered: ['88/1'],
      totalAreaHandedOverHectares: 4.80,
      encroachmentsCleared: true,
      encumbranceFreeCertificateIssued: true,
      status: 'Handed Over to Implementing Agency',
      officerInCharge: 'Shri D. K. Jena, OAS',
      agencyRepresentative: 'Director (Estate), DRDO',
      form11CertificateUrl: '/documents/form11_possession_drdo.pdf'
    }
  ];

  // Add more possessions up to 10
  for (let i = 5; i <= 10; i++) {
    const projIndex = (i % 10);
    const p = projects[projIndex];
    possessions.push({
      _id: `pos_00${i}`,
      id: `pos_00${i}`,
      possessionId: `POS-2024-00${i}`,
      possessionCertificateNumber: `FORM-11-${p.district.substring(0, 3).toUpperCase()}-2024-00${i}`,
      projectId: p.projectId,
      section38NoticeDate: new Date('2024-08-15'),
      physicalPossessionDate: new Date('2024-09-01'),
      handoverToAgencyDate: new Date('2024-09-10'),
      khasraNumbersCovered: [`${i * 5}/1`],
      totalAreaHandedOverHectares: Number((3.5 + (i * 0.5)).toFixed(2)),
      encroachmentsCleared: true,
      encumbranceFreeCertificateIssued: true,
      status: 'Handed Over to Implementing Agency',
      officerInCharge: `Deputy Collector & CALA, ${p.district}`,
      agencyRepresentative: `Project Director, ${p.implementingAgency}`,
      form11CertificateUrl: `/documents/form11_${p.projectId}.pdf`
    });
  }

  // 10. 14 R&R CASES (Second Schedule Entitlements)
  const rrCases = [
    {
      _id: 'rrc_001',
      id: 'rrc_001',
      rrCaseNumber: 'RRC-2024-001',
      projectId: 'PRJ-NHAI-DME-001',
      familyRegistrationId: 'PAF-MH-THN-001',
      familyHeadName: 'Shri Tukaram Balaram Patil',
      village: 'Padgha',
      resettlementHouseAllotted: false,
      cashGrantInLieuOfHouse: 0,
      subsistenceAllowanceAmount: 36000,
      subsistenceAllowanceStatus: 'Disbursed',
      transportationAllowanceAmount: 50000,
      transportationAllowanceStatus: 'Disbursed',
      cattleShedPettyShopGrant: 25000,
      livelihoodSettlement: 'One-time Lump Sum Grant (₹5,00,000)',
      livelihoodStatus: 'Settled / Disbursed',
      caseStatus: 'Fully Settled',
      settlementDate: new Date('2024-11-25')
    },
    {
      _id: 'rrc_002',
      id: 'rrc_002',
      rrCaseNumber: 'RRC-2024-002',
      projectId: 'PRJ-NHAI-DME-001',
      familyRegistrationId: 'PAF-MH-THN-002',
      familyHeadName: 'Smt. Shantabai Kashinath Mhatre',
      village: 'Padgha',
      resettlementHouseAllotted: true,
      allottedPlotNumber: 'PLOT-BHW-R&R-Sec2-44',
      subsistenceAllowanceAmount: 36000,
      subsistenceAllowanceStatus: 'Disbursed',
      transportationAllowanceAmount: 50000,
      transportationAllowanceStatus: 'Disbursed',
      cattleShedPettyShopGrant: 25000,
      livelihoodSettlement: 'One-time Lump Sum Grant (₹5,00,000)',
      livelihoodStatus: 'Settled / Disbursed',
      caseStatus: 'Disbursement In Progress',
      settlementDate: new Date('2024-12-01')
    }
  ];

  for (let i = 3; i <= 14; i++) {
    const projIndex = (i % 10);
    const p = projects[projIndex];
    rrCases.push({
      _id: `rrc_00${i}`,
      id: `rrc_00${i}`,
      rrCaseNumber: `RRC-2024-00${i}`,
      projectId: p.projectId,
      familyRegistrationId: `PAF-${p.state.substring(0, 2).toUpperCase()}-${p.district.substring(0, 3).toUpperCase()}-0${i}`,
      familyHeadName: `Family Head ${i}`,
      village: p.village,
      resettlementHouseAllotted: i % 2 === 0,
      allottedPlotNumber: i % 2 === 0 ? `PLOT-${p.district.substring(0, 3).toUpperCase()}-${i}` : undefined,
      subsistenceAllowanceAmount: 36000,
      subsistenceAllowanceStatus: i > 6 ? 'Disbursed' : 'Pending',
      transportationAllowanceAmount: 50000,
      transportationAllowanceStatus: i > 6 ? 'Disbursed' : 'Pending',
      livelihoodSettlement: 'One-time Lump Sum Grant (₹5,00,000)',
      livelihoodStatus: i > 8 ? 'Settled / Disbursed' : 'Pending Settlement',
      caseStatus: i > 8 ? 'Fully Settled' : 'Scheme Approved',
      settlementDate: i > 8 ? new Date('2024-10-15') : undefined
    });
  }

  // 11. 18 OFFICIAL STATUTORY DOCUMENTS ARCHIVE
  const documents = [
    {
      _id: 'doc_001',
      id: 'doc_001',
      documentId: 'DOC-DME-001',
      projectId: 'PRJ-NHAI-DME-001',
      title: 'Gazette Notification S.O. 1245(E) - Section 11(1)',
      documentType: 'Gazette Notification (Sec 11)',
      statutorySection: 'Section 11(1)',
      fileNumber: 'RW/NHAI/DME/PKG14/SEC11',
      fileSize: '3.4 MB',
      fileUrl: '/documents/gazette_sec11_dme.pdf',
      uploadedBy: 'Shri Suresh K. Patil, CALA',
      verificationStatus: 'Verified Official'
    },
    {
      _id: 'doc_002',
      id: 'doc_002',
      documentId: 'DOC-DME-002',
      projectId: 'PRJ-NHAI-DME-001',
      title: 'Statutory Declaration S.O. 3892(E) - Section 19(1)',
      documentType: 'Statutory Declaration (Sec 19)',
      statutorySection: 'Section 19(1)',
      fileNumber: 'RW/NHAI/DME/PKG14/SEC19',
      fileSize: '4.1 MB',
      fileUrl: '/documents/gazette_sec19_dme.pdf',
      uploadedBy: 'Govt of Maharashtra',
      verificationStatus: 'Verified Official'
    },
    {
      _id: 'doc_003',
      id: 'doc_003',
      documentId: 'DOC-DME-003',
      projectId: 'PRJ-NHAI-DME-001',
      title: 'Section 23 Final Award Determination Decree',
      documentType: 'Section 23 Award Ledger',
      statutorySection: 'Section 23 & 30',
      fileNumber: 'CALA/BHW/AWD/2024/01',
      fileSize: '8.2 MB',
      fileUrl: '/documents/award_sec23_dme.pdf',
      uploadedBy: 'CALA Office Thane',
      verificationStatus: 'Verified Official'
    },
    {
      _id: 'doc_004',
      id: 'doc_004',
      documentId: 'DOC-DME-004',
      projectId: 'PRJ-NHAI-DME-001',
      title: 'Form 11 Certificate of Physical Possession',
      documentType: 'Form 11 Possession Certificate',
      statutorySection: 'Section 38',
      fileNumber: 'FORM-11/THN/2024/042',
      fileSize: '1.8 MB',
      fileUrl: '/documents/form11_possession_dme.pdf',
      uploadedBy: 'Collector Office Thane',
      verificationStatus: 'Verified Official'
    },
    {
      _id: 'doc_005',
      id: 'doc_005',
      documentId: 'DOC-DME-005',
      projectId: 'PRJ-NHAI-DME-001',
      title: 'Comprehensive Social Impact Assessment (SIA) DPR',
      documentType: 'Social Impact Assessment (SIA) Report',
      statutorySection: 'Section 4(1)',
      fileNumber: 'SIA/TISS/DME/2024',
      fileSize: '14.5 MB',
      fileUrl: '/documents/sia_report_dme.pdf',
      uploadedBy: 'Tata Institute of Social Sciences (TISS)',
      verificationStatus: 'Verified Official'
    },
    {
      _id: 'doc_006',
      id: 'doc_006',
      documentId: 'DOC-DME-006',
      projectId: 'PRJ-NHAI-DME-001',
      title: 'PFMS DBT Batch Disbursal Mandate Slip',
      documentType: 'PFMS DBT Disbursal Mandate',
      statutorySection: 'PFMS DBT',
      fileNumber: 'PFMS/MH/NHAI/2024/BATCH1',
      fileSize: '2.2 MB',
      fileUrl: '/documents/pfms_dbt_dme.pdf',
      uploadedBy: 'Accounts Officer, CALA',
      verificationStatus: 'Verified Official'
    }
  ];

  for (let i = 7; i <= 18; i++) {
    const projIndex = (i % 10);
    const p = projects[projIndex];
    documents.push({
      _id: `doc_0${i}`,
      id: `doc_0${i}`,
      documentId: `DOC-${p.district.substring(0, 3).toUpperCase()}-0${i}`,
      projectId: p.projectId,
      title: `Official Statutory Gazette / File ${i} - ${p.projectName}`,
      documentType: i % 2 === 0 ? 'Gazette Notification (Sec 11)' : 'Statutory Declaration (Sec 19)',
      statutorySection: i % 2 === 0 ? 'Section 11(1)' : 'Section 19(1)',
      fileNumber: `FILE/${p.district.substring(0, 3).toUpperCase()}/2024/${i}`,
      fileSize: `${(2.1 + (i * 0.3)).toFixed(1)} MB`,
      fileUrl: `/documents/statutory_${p.projectId}.pdf`,
      uploadedBy: `State Revenue Dept, ${p.state}`,
      verificationStatus: 'Verified Official'
    });
  }

  // 12. 35 STATUTORY TIMELINE MILESTONES ACROSS PROJECTS
  const milestones = [
    {
      _id: 'mls_001',
      id: 'mls_001',
      milestoneId: 'MLS-DME-01',
      projectId: 'PRJ-NHAI-DME-001',
      stageCode: 'SEC_3A_PROPOSAL',
      title: 'Alignment Feasibility & Project Proposal Submission',
      statutoryReference: 'RFCTLARR Sec 3(A)',
      targetDate: new Date('2024-02-15'),
      actualDate: new Date('2024-02-10'),
      status: 'Completed',
      actionOfficer: 'Er. Manoj Verma, NHAI'
    },
    {
      _id: 'mls_002',
      id: 'mls_002',
      milestoneId: 'MLS-DME-02',
      projectId: 'PRJ-NHAI-DME-001',
      stageCode: 'SEC_4_SIA',
      title: 'Social Impact Assessment Study & Expert Committee Review',
      statutoryReference: 'RFCTLARR Sec 4(1) & Sec 7',
      targetDate: new Date('2024-05-10'),
      actualDate: new Date('2024-05-02'),
      status: 'Completed',
      actionOfficer: 'TISS Research Team'
    },
    {
      _id: 'mls_003',
      id: 'mls_003',
      milestoneId: 'MLS-DME-03',
      projectId: 'PRJ-NHAI-DME-001',
      stageCode: 'SEC_11_NOTIFICATION',
      title: 'Publication of Preliminary Gazette Notification',
      statutoryReference: 'RFCTLARR Sec 11(1)',
      targetDate: new Date('2024-07-01'),
      actualDate: new Date('2024-06-25'),
      status: 'Completed',
      actionOfficer: 'Shri Suresh K. Patil, CALA'
    },
    {
      _id: 'mls_004',
      id: 'mls_004',
      milestoneId: 'MLS-DME-04',
      projectId: 'PRJ-NHAI-DME-001',
      stageCode: 'SEC_15_OBJECTIONS',
      title: 'Hearing of Landowner Objections & Report to Collector',
      statutoryReference: 'RFCTLARR Sec 15(2)',
      targetDate: new Date('2024-09-01'),
      actualDate: new Date('2024-08-28'),
      status: 'Completed',
      actionOfficer: 'Shri Suresh K. Patil, CALA'
    },
    {
      _id: 'mls_005',
      id: 'mls_005',
      milestoneId: 'MLS-DME-05',
      projectId: 'PRJ-NHAI-DME-001',
      stageCode: 'SEC_19_DECLARATION',
      title: 'Statutory Declaration of Resettlement & Acquisition',
      statutoryReference: 'RFCTLARR Sec 19(1)',
      targetDate: new Date('2024-11-01'),
      actualDate: new Date('2024-10-20'),
      status: 'Completed',
      actionOfficer: 'Govt of Maharashtra'
    },
    {
      _id: 'mls_006',
      id: 'mls_006',
      milestoneId: 'MLS-DME-06',
      projectId: 'PRJ-NHAI-DME-001',
      stageCode: 'SEC_23_AWARD',
      title: 'Enquiry and Passing of Final Land Acquisition Award',
      statutoryReference: 'RFCTLARR Sec 23 & 30',
      targetDate: new Date('2024-12-15'),
      actualDate: new Date('2024-11-15'),
      status: 'Completed',
      actionOfficer: 'Shri Suresh K. Patil, CALA'
    },
    {
      _id: 'mls_007',
      id: 'mls_007',
      milestoneId: 'MLS-DME-07',
      projectId: 'PRJ-NHAI-DME-001',
      stageCode: 'SEC_30_COMPENSATION',
      title: 'Direct Benefit Transfer (DBT) of 100% Solatium via PFMS',
      statutoryReference: 'RFCTLARR Sec 30(1) & PFMS',
      targetDate: new Date('2025-01-30'),
      status: 'In Progress',
      actionOfficer: 'Accounts Officer, CALA'
    },
    {
      _id: 'mls_008',
      id: 'mls_008',
      milestoneId: 'MLS-DME-08',
      projectId: 'PRJ-NHAI-DME-001',
      stageCode: 'SEC_38_POSSESSION',
      title: 'Physical Possession Handover & Form 11 Execution',
      statutoryReference: 'RFCTLARR Sec 38',
      targetDate: new Date('2025-03-31'),
      status: 'Pending',
      actionOfficer: 'Collector Office Thane'
    }
  ];

  // Add milestones for remaining 9 projects
  for (let pIdx = 1; pIdx < projects.length; pIdx++) {
    const p = projects[pIdx];
    const stages = [
      { code: 'SEC_3A_PROPOSAL', title: 'Proposal Submission & Vetting', ref: 'Sec 3A' },
      { code: 'SEC_4_SIA', title: 'Social Impact Assessment Study', ref: 'Sec 4(1)' },
      { code: 'SEC_11_NOTIFICATION', title: 'Preliminary Gazette Publication', ref: 'Sec 11(1)' },
      { code: 'SEC_19_DECLARATION', title: 'Statutory Declaration Decree', ref: 'Sec 19(1)' },
      { code: 'SEC_23_AWARD', title: 'Final Section 23 Award Order', ref: 'Sec 23 & 30' },
      { code: 'SEC_38_POSSESSION', title: 'Physical Possession Handover', ref: 'Sec 38' }
    ];

    stages.forEach((st, sIdx) => {
      milestones.push({
        _id: `mls_${p.projectId}_0${sIdx + 1}`,
        id: `mls_${p.projectId}_0${sIdx + 1}`,
        milestoneId: `MLS-${p.projectId}-0${sIdx + 1}`,
        projectId: p.projectId,
        stageCode: st.code,
        title: st.title,
        statutoryReference: st.ref,
        targetDate: new Date(Date.now() + (sIdx * 60 - 120) * 86400000),
        actualDate: sIdx < 3 ? new Date(Date.now() + (sIdx * 60 - 130) * 86400000) : undefined,
        status: sIdx < 3 ? 'Completed' : (sIdx === 3 ? 'In Progress' : 'Pending'),
        actionOfficer: `CALA & Collector, ${p.district}`
      });
    });
  }

  // 13. AUDIT LOGS (Immutable event trail)
  const auditLogs = [
    {
      _id: 'aud_001',
      id: 'aud_001',
      timestamp: new Date('2024-11-28T14:30:00Z'),
      userId: 'user_005',
      userName: 'Shri Suresh K. Patil',
      userRole: 'LAND_ACQUISITION_OFFICER',
      action: 'DBT_DISBURSED',
      resourceType: 'Compensation',
      resourceId: 'PRJ-NHAI-DME-001',
      description: 'PFMS DBT Batch Disbursal of ₹3,37,79,200 credited to Shri Tukaram Balaram Patil (Khasra 42/1).',
      metadata: { projectId: 'PRJ-NHAI-DME-001', amount: 33779200, khasra: '42/1' }
    },
    {
      _id: 'aud_002',
      id: 'aud_002',
      timestamp: new Date('2024-11-15T11:00:00Z'),
      userId: 'user_005',
      userName: 'Shri Suresh K. Patil',
      userRole: 'LAND_ACQUISITION_OFFICER',
      action: 'AWARD_DETERMINED',
      resourceType: 'Award',
      resourceId: 'PRJ-NHAI-DME-001',
      description: 'Section 23 Final Award passed for 8.20 Ha (Padgha village). Total Award ₹9.68 Cr with 100% Solatium.',
      metadata: { projectId: 'PRJ-NHAI-DME-001', awardNumber: 'AWD-THN-SEC23-2024-001' }
    },
    {
      _id: 'aud_003',
      id: 'aud_003',
      timestamp: new Date('2024-10-20T16:15:00Z'),
      userId: 'user_003',
      userName: 'Shri Vikramaditya Jadhav, IAS',
      userRole: 'STATE_GOV_OFFICER',
      action: 'SECTION_19_DECLARED',
      resourceType: 'Notification',
      resourceId: 'PRJ-NHAI-DME-001',
      description: 'Gazette Declaration S.O. 3892(E) published under Section 19(1) of RFCTLARR Act 2013.',
      metadata: { projectId: 'PRJ-NHAI-DME-001', gazette: 'S.O. 3892(E)' }
    },
    {
      _id: 'aud_004',
      id: 'aud_004',
      timestamp: new Date('2024-03-15T10:00:00Z'),
      userId: 'user_004',
      userName: 'Shri Ashok Kumar Meena, IAS',
      userRole: 'DISTRICT_AUTHORITY_OFFICER',
      action: 'SECTION_11_NOTIFIED',
      resourceType: 'Notification',
      resourceId: 'PRJ-NHAI-DME-001',
      description: 'Preliminary Notification S.O. 1245(E) published. 60-day objection clock activated.',
      metadata: { projectId: 'PRJ-NHAI-DME-001', gazette: 'S.O. 1245(E)' }
    },
    {
      _id: 'aud_005',
      id: 'aud_005',
      timestamp: new Date('2024-02-05T09:30:00Z'),
      userId: 'user_004',
      userName: 'Shri Ashok Kumar Meena, IAS',
      userRole: 'DISTRICT_AUTHORITY_OFFICER',
      action: 'PROPOSAL_VERIFIED',
      resourceType: 'Proposal',
      resourceId: 'PRJ-NHAI-DME-001',
      description: 'District Collector verified alignment land records against RoR 7/12 records. Transferred to State Review.',
      metadata: { projectId: 'PRJ-NHAI-DME-001', proposalId: 'PROP-2024-001' }
    }
  ];

  // 14. NOTIFICATION ALERTS FOR OFFICERS
  const notificationAlerts = [
    {
      _id: 'alt_001',
      alertId: 'ALT-2024-001',
      recipientRole: 'DISTRICT_AUTHORITY_OFFICER',
      projectId: 'PRJ-NHAI-DME-001',
      title: 'Action Required: Section 15 Hearing Summary',
      message: 'Hearing of objections report for Padgha village corridor submitted by CALA for your review.',
      alertType: 'ACTION_REQUIRED',
      isRead: false,
      link: '/projects/PRJ-NHAI-DME-001'
    },
    {
      _id: 'alt_002',
      alertId: 'ALT-2024-002',
      recipientRole: 'LAND_ACQUISITION_OFFICER',
      projectId: 'PRJ-UPEIDA-GNGA-003',
      title: 'Statutory Clock: Section 11 to 19 Countdown',
      message: '8 months elapsed since Section 11 notice. Section 19 declaration must be passed before lapse date.',
      alertType: 'STATUTORY_DEADLINE',
      isRead: false,
      link: '/projects/PRJ-UPEIDA-GNGA-003'
    }
  ];

  return {
    users,
    projects,
    proposals,
    landParcels,
    notifications,
    awards,
    compensations,
    affectedFamilies,
    possessions,
    rrCases,
    documents,
    milestones,
    auditLogs,
    notificationAlerts
  };
}

module.exports = { getSeedData };
