const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  CENTRAL_MINISTRY_OFFICER: 'CENTRAL_MINISTRY_OFFICER',
  STATE_GOV_OFFICER: 'STATE_GOV_OFFICER',
  DISTRICT_AUTHORITY_OFFICER: 'DISTRICT_AUTHORITY_OFFICER',
  LAND_ACQUISITION_OFFICER: 'LAND_ACQUISITION_OFFICER',
  PROJECT_AGENCY_OFFICER: 'PROJECT_AGENCY_OFFICER',
  FIELD_SURVEY_OFFICER: 'FIELD_SURVEY_OFFICER',
  VIEWER_EXECUTIVE: 'VIEWER_EXECUTIVE'
};

const PERMISSIONS = {
  // Projects & Proposals
  VIEW_PROJECTS: 'VIEW_PROJECTS',
  CREATE_PROJECTS: 'CREATE_PROJECTS',
  SUBMIT_PROPOSALS: 'SUBMIT_PROPOSALS',
  APPROVE_PROPOSALS: 'APPROVE_PROPOSALS',
  ADVANCE_STATUTORY_STAGE: 'ADVANCE_STATUTORY_STAGE',

  // Cadastral & Survey
  VIEW_PARCELS: 'VIEW_PARCELS',
  EDIT_PARCEL: 'EDIT_PARCEL',
  GEOTAG_FIELD_SURVEY: 'GEOTAG_FIELD_SURVEY',
  VIEW_GIS_MAP: 'VIEW_GIS_MAP',

  // Statutory Workflow
  PUBLISH_SECTION_11: 'PUBLISH_SECTION_11',
  HEAR_SECTION_15_OBJECTIONS: 'HEAR_SECTION_15_OBJECTIONS',
  DECLARE_SECTION_19: 'DECLARE_SECTION_19',
  VIEW_NOTIFICATIONS: 'VIEW_NOTIFICATIONS',

  // Awards & Compensation
  CALCULATE_SOLATIUM: 'CALCULATE_SOLATIUM',
  PASS_SECTION_23_AWARD: 'PASS_SECTION_23_AWARD',
  DISBURSE_PFMS_DBT: 'DISBURSE_PFMS_DBT',

  // Physical Possession
  ISSUE_POSSESSION_CERTIFICATE: 'ISSUE_POSSESSION_CERTIFICATE',
  VIEW_POSSESSION: 'VIEW_POSSESSION',

  // R&R
  VIEW_RR: 'VIEW_RR',
  MANAGE_RR: 'MANAGE_RR',
  VIEW_FAMILIES: 'VIEW_FAMILIES',
  ENROLL_FAMILY: 'ENROLL_FAMILY',

  // Intelligence & Administration
  VIEW_DOCUMENTS: 'VIEW_DOCUMENTS',
  VIEW_REPORTS: 'VIEW_REPORTS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  ADMIN_SETTINGS: 'ADMIN_SETTINGS'
};

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.CENTRAL_MINISTRY_OFFICER]: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.CREATE_PROJECTS,
    PERMISSIONS.SUBMIT_PROPOSALS,
    PERMISSIONS.APPROVE_PROPOSALS,
    PERMISSIONS.VIEW_GIS_MAP,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],

  [ROLES.STATE_GOV_OFFICER]: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.CREATE_PROJECTS,
    PERMISSIONS.APPROVE_PROPOSALS,
    PERMISSIONS.ADVANCE_STATUTORY_STAGE,
    PERMISSIONS.VIEW_PARCELS,
    PERMISSIONS.VIEW_GIS_MAP,
    PERMISSIONS.PUBLISH_SECTION_11,
    PERMISSIONS.DECLARE_SECTION_19,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],

  [ROLES.DISTRICT_AUTHORITY_OFFICER]: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.APPROVE_PROPOSALS,
    PERMISSIONS.ADVANCE_STATUTORY_STAGE,
    PERMISSIONS.VIEW_PARCELS,
    PERMISSIONS.EDIT_PARCEL,
    PERMISSIONS.VIEW_GIS_MAP,
    PERMISSIONS.PUBLISH_SECTION_11,
    PERMISSIONS.HEAR_SECTION_15_OBJECTIONS,
    PERMISSIONS.DECLARE_SECTION_19,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.CALCULATE_SOLATIUM,
    PERMISSIONS.PASS_SECTION_23_AWARD,
    PERMISSIONS.VIEW_POSSESSION,
    PERMISSIONS.ISSUE_POSSESSION_CERTIFICATE,
    PERMISSIONS.VIEW_RR,
    PERMISSIONS.MANAGE_RR,
    PERMISSIONS.VIEW_FAMILIES,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],

  [ROLES.LAND_ACQUISITION_OFFICER]: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.ADVANCE_STATUTORY_STAGE,
    PERMISSIONS.VIEW_PARCELS,
    PERMISSIONS.EDIT_PARCEL,
    PERMISSIONS.VIEW_GIS_MAP,
    PERMISSIONS.PUBLISH_SECTION_11,
    PERMISSIONS.HEAR_SECTION_15_OBJECTIONS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.CALCULATE_SOLATIUM,
    PERMISSIONS.PASS_SECTION_23_AWARD,
    PERMISSIONS.DISBURSE_PFMS_DBT,
    PERMISSIONS.VIEW_POSSESSION,
    PERMISSIONS.ISSUE_POSSESSION_CERTIFICATE,
    PERMISSIONS.VIEW_RR,
    PERMISSIONS.MANAGE_RR,
    PERMISSIONS.VIEW_FAMILIES,
    PERMISSIONS.ENROLL_FAMILY,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],

  [ROLES.PROJECT_AGENCY_OFFICER]: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.CREATE_PROJECTS,
    PERMISSIONS.SUBMIT_PROPOSALS,
    PERMISSIONS.VIEW_PARCELS,
    PERMISSIONS.VIEW_GIS_MAP,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.CALCULATE_SOLATIUM,
    PERMISSIONS.DISBURSE_PFMS_DBT,
    PERMISSIONS.VIEW_POSSESSION,
    PERMISSIONS.VIEW_RR,
    PERMISSIONS.VIEW_FAMILIES,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS
  ],

  [ROLES.FIELD_SURVEY_OFFICER]: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.VIEW_PARCELS,
    PERMISSIONS.EDIT_PARCEL,
    PERMISSIONS.GEOTAG_FIELD_SURVEY,
    PERMISSIONS.VIEW_GIS_MAP,
    PERMISSIONS.VIEW_FAMILIES,
    PERMISSIONS.ENROLL_FAMILY,
    PERMISSIONS.VIEW_DOCUMENTS
  ],

  [ROLES.VIEWER_EXECUTIVE]: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.VIEW_GIS_MAP,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS
  ]
};

const ROLE_DETAILS = {
  [ROLES.SUPER_ADMIN]: {
    name: 'Super Administrator',
    badge: 'National DG / Super Admin',
    description: 'Full statutory and administrative access to all modules, users, security parameters, and audit trails.',
    scope: 'National Authority'
  },
  [ROLES.CENTRAL_MINISTRY_OFFICER]: {
    name: 'Central Ministry Officer',
    badge: 'Ministry Officer (MoRTH/Railways)',
    description: 'National-level infrastructure alignment oversight, portfolio dashboard, reports, approvals, and analytics.',
    scope: 'National Infrastructure'
  },
  [ROLES.STATE_GOV_OFFICER]: {
    name: 'State Government Officer',
    badge: 'State Revenue Department',
    description: 'State-level infrastructure oversight, statutory gazette approvals, district monitoring, and returns.',
    scope: 'State Jurisdiction'
  },
  [ROLES.DISTRICT_AUTHORITY_OFFICER]: {
    name: 'District Authority Officer',
    badge: 'District Collector & DM',
    description: 'District project jurisdiction, Section 11/19 approvals, objection hearings, award verification, and R&R sanctions.',
    scope: 'District Revenue Administration'
  },
  [ROLES.LAND_ACQUISITION_OFFICER]: {
    name: 'Land Acquisition Officer',
    badge: 'CALA / SLAO Officer',
    description: 'Complete statutory acquisition workflow, Gazette notifications, Section 23 awards, 100% solatium, and PFMS DBT.',
    scope: 'Special Land Acquisition Office'
  },
  [ROLES.PROJECT_AGENCY_OFFICER]: {
    name: 'Project Implementing Agency',
    badge: 'Implementing Agency (NHAI/DFC)',
    description: 'Project proposal initiation, acquisition funding, GIS alignment coordinates upload, and possession receipt.',
    scope: 'PIU / Implementing Entity'
  },
  [ROLES.FIELD_SURVEY_OFFICER]: {
    name: 'Field Survey Officer',
    badge: 'Revenue Amin / Cadastral Surveyor',
    description: 'Ground cadastral verification, GPS geotagged survey sheets, trees & structures census, and PAF enumeration.',
    scope: 'Tehsil / Cadastral Field Office'
  },
  [ROLES.VIEWER_EXECUTIVE]: {
    name: 'Viewer / Executive Monitor',
    badge: 'Executive Viewer (PM GatiShakti)',
    description: 'Read-only access to GIS cadastral overlays, timeline progress, financial disbursements, and executive reports.',
    scope: 'Executive Oversight'
  }
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  ROLE_DETAILS
};
